namespace FMOD
{
	public enum DSP_PARAMETER_FLOAT_MAPPING_TYPE
	{
		DSP_PARAMETER_FLOAT_MAPPING_TYPE_LINEAR = 0,
		DSP_PARAMETER_FLOAT_MAPPING_TYPE_AUTO = 1,
		DSP_PARAMETER_FLOAT_MAPPING_TYPE_PIECEWISE_LINEAR = 2
	}
}
