namespace FMOD
{
	public enum DSP_MULTIBAND_EQ_FILTER_TYPE
	{
		DISABLED = 0,
		LOWPASS_12DB = 1,
		LOWPASS_24DB = 2,
		LOWPASS_48DB = 3,
		HIGHPASS_12DB = 4,
		HIGHPASS_24DB = 5,
		HIGHPASS_48DB = 6,
		LOWSHELF = 7,
		HIGHSHELF = 8,
		PEAKING = 9,
		BANDPASS = 10,
		NOTCH = 11,
		ALLPASS = 12
	}
}
