namespace FMOD.Studio
{
	public enum PARAMETER_TYPE
	{
		GAME_CONTROLLED = 0,
		AUTOMATIC_DISTANCE = 1,
		AUTOMATIC_EVENT_CONE_ANGLE = 2,
		AUTOMATIC_EVENT_ORIENTATION = 3,
		AUTOMATIC_DIRECTION = 4,
		AUTOMATIC_ELEVATION = 5,
		AUTOMATIC_LISTENER_ORIENTATION = 6,
		AUTOMATIC_SPEED = 7,
		AUTOMATIC_SPEED_ABSOLUTE = 8,
		AUTOMATIC_DISTANCE_NORMALIZED = 9,
		MAX = 10
	}
}
