namespace GLTFast.Logging
{
	public enum LogCode : uint
	{
		None = 0u,
		AccessorAttributeTypeUnknown = 1u,
		AccessorInconsistentUsage = 2u,
		AccessorsShared = 3u,
		AnimationChannelNodeInvalid = 4u,
		AnimationChannelSamplerInvalid = 5u,
		AnimationFormatInvalid = 6u,
		AnimationTargetPathUnsupported = 7u,
		BufferLoadFailed = 8u,
		BufferMainInvalidType = 9u,
		ChunkJsonInvalid = 10u,
		ChunkIncomplete = 11u,
		ChunkUnknown = 12u,
		ColorFormatUnsupported = 13u,
		Download = 14u,
		EmbedBufferLoadFailed = 15u,
		EmbedImageInconsistentType = 16u,
		EmbedImageLoadFailed = 17u,
		EmbedImageUnsupportedType = 18u,
		EmbedSlow = 19u,
		ExtensionUnsupported = 20u,
		ExportImageFailed = 21u,
		GltfNotBinary = 22u,
		GltfUnsupportedVersion = 23u,
		HierarchyInvalid = 24u,
		ImageConversionNotEnabled = 25u,
		ImageFormatUnknown = 26u,
		ImageMultipleSamplers = 27u,
		IndexFormatInvalid = 28u,
		JsonParsingFailed = 29u,
		MaterialTransmissionApprox = 30u,
		MaterialTransmissionApproxUrp = 31u,
		MeshBoundsMissing = 32u,
		MeshNotReadable = 33u,
		MissingImageURL = 34u,
		MorphTargetContextFail = 35u,
		NamingOverride = 36u,
		PackageMissing = 37u,
		PrimitiveModeUnsupported = 38u,
		RemapUnsupported = 39u,
		ShaderMissing = 40u,
		SkinMissing = 41u,
		SparseAccessor = 42u,
		TextureDownloadFailed = 43u,
		TextureInvalidType = 44u,
		TextureLoadFailed = 45u,
		TextureNotFound = 46u,
		TopologyPointsMaterialUnsupported = 47u,
		TopologyUnsupported = 48u,
		TypeUnsupported = 49u,
		UnityWebRequestTextureNotEnabled = 50u,
		UVLimit = 51u,
		UVMulti = 52u,
		UncompressedFallbackNotSupported = 53u,
		InconsistentVertexColorUsage = 54u,
		StreamError = 55u
	}
}
