<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>Assembly-CSharp</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net35</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>4</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnityEngine">
      <HintPath>..\..\Assemblies\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>..\..\Assemblies\Assembly-CSharp-firstpass.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>..\..\Assemblies\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="mcs">
      <HintPath>..\..\Assemblies\mcs.dll</HintPath>
    </Reference>
    <Reference Include="DynamicText">
      <HintPath>..\..\Assemblies\DynamicText.dll</HintPath>
    </Reference>
    <Reference Include="Mono.Cecil">
      <HintPath>..\..\Assemblies\Mono.Cecil.dll</HintPath>
    </Reference>
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Xml" />
    <Reference Include="Open.Nat">
      <HintPath>..\..\Assemblies\Open.Nat.dll</HintPath>
    </Reference>
    <Reference Include="RakNetSwig">
      <HintPath>..\..\Assemblies\RakNetSwig.dll</HintPath>
    </Reference>
    <Reference Include="System.Threading">
      <HintPath>..\..\Assemblies\System.Threading.dll</HintPath>
    </Reference>
    <Reference Include="ch.sycoforge.Decal">
      <HintPath>..\..\Assemblies\ch.sycoforge.Decal.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.Networking">
      <HintPath>..\..\Assemblies\UnityEngine.Networking.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\..\Assemblies\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="Ookii.Dialogs">
      <HintPath>..\..\Assemblies\Ookii.Dialogs.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>