using System;
using MagicaCloth2;
using Unity.Jobs;
using Unity.Mathematics;
using UnityEngine;
using UnityEngine.Jobs;

[Unity.Jobs.DOTSCompilerGenerated]
internal class __JobReflectionRegistrationOutput__13630703774553276063
{
	public static void CreateJobReflectionData()
	{
		try
		{
			IJobParallelForExtensions.EarlyJobInit<ClothProcess.GenerateSelectionJob>();
			IJobParallelForExtensions.EarlyJobInit<SelfCollisionConstraint.InitPrimitiveJob>();
			IJobParallelForExtensions.EarlyJobInit<SelfCollisionConstraint.SelfStep_UpdatePrimitiveJob>();
			IJobParallelForExtensions.EarlyJobInit<SelfCollisionConstraint.SelfStep_UpdateGridJob>();
			IJobParallelForExtensions.EarlyJobInit<SelfCollisionConstraint.SelfStep_DetectionContactJob>();
			IJobExtensions.EarlyJobInit<SelfCollisionConstraint.SelfStep_ConvertContactListJob>();
			IJobParallelForDeferExtensions.EarlyJobInit<SelfCollisionConstraint.SelfStep_UpdateContactJob>();
			IJobParallelForDeferExtensions.EarlyJobInit<SelfCollisionConstraint.SelfStep_SolverContactJob>();
			IJobParallelForExtensions.EarlyJobInit<SelfCollisionConstraint.SelfStep_SumContactJob>();
			IJobParallelForExtensions.EarlyJobInit<SelfCollisionConstraint.SelfDetectionIntersectJob>();
			IJobExtensions.EarlyJobInit<SelfCollisionConstraint.SelfConvertIntersectListJob>();
			IJobParallelForExtensions.EarlyJobInit<SelfCollisionConstraint.SelfClearIntersectJob>();
			IJobParallelForDeferExtensions.EarlyJobInit<SelfCollisionConstraint.SelfSolverIntersectJob>();
			IJobParallelForExtensions.EarlyJobInit<SelectionData.TransformPositionJob>();
			IJobExtensions.EarlyJobInit<SelectionData.CreateGridMapJob>();
			IJobParallelForExtensions.EarlyJobInit<SelectionData.ConvertSelectionJob>();
			IJobParallelForExtensions.EarlyJobInit<RenderSetupData.CalcInverseRotationJob>();
			IJobParallelForTransformExtensions.EarlyJobInit<RenderSetupData.ReadTransformJob>();
			IJobExtensions.EarlyJobInit<RenderSetupData.GetBoneWeightJos>();
			IJobExtensions.EarlyJobInit<RenderSetupSerializeData.CalcUseBoneArrayJob2>();
			IJobParallelForExtensions.EarlyJobInit<SimulationManager.SimulationNormalJob>();
			IJobParallelForExtensions.EarlyJobInit<SimulationManager.SplitPre_A_Job>();
			IJobParallelForExtensions.EarlyJobInit<SimulationManager.SplitPre_B_Job>();
			IJobParallelForExtensions.EarlyJobInit<SimulationManager.SplitPre_C_Job>();
			IJobParallelForExtensions.EarlyJobInit<SimulationManager.SplitStep_A_Job>();
			IJobParallelForExtensions.EarlyJobInit<SimulationManager.SplitStep_B_Job>();
			IJobParallelForExtensions.EarlyJobInit<SimulationManager.SplitStep_C_Job>();
			IJobParallelForExtensions.EarlyJobInit<SimulationManager.SplitStep_D_Job>();
			IJobParallelForExtensions.EarlyJobInit<SimulationManager.SplitStep_Angle_Job>();
			IJobParallelForExtensions.EarlyJobInit<SimulationManager.SplitStep_Triangle_Job>();
			IJobParallelForExtensions.EarlyJobInit<SimulationManager.SplitStep_E_Job>();
			IJobParallelForExtensions.EarlyJobInit<SimulationManager.SplitStep_Edge_Job>();
			IJobParallelForExtensions.EarlyJobInit<SimulationManager.SplitStep_F_Self_Job>();
			IJobParallelForExtensions.EarlyJobInit<SimulationManager.SplitStep_G_Self_Job>();
			IJobParallelForExtensions.EarlyJobInit<SimulationManager.SplitStep_FG_NoSelf_Job>();
			IJobParallelForExtensions.EarlyJobInit<SimulationManager.SplitPost_DisplayPos_Job>();
			IJobParallelForExtensions.EarlyJobInit<SimulationManager.SplitPost_CalcProxy_Job>();
			IJobParallelForExtensions.EarlyJobInit<SimulationManager.SplitPost_CalcProxyTriangle_Job>();
			IJobParallelForExtensions.EarlyJobInit<SimulationManager.SplitPost_SumProxyTriangleAndTransform_Job>();
			IJobParallelForExtensions.EarlyJobInit<SimulationManager.SplitPost_TeamCollider_Job>();
			IJobExtensions.EarlyJobInit<TeamManager.AlwaysTeamUpdatePreJob>();
			IJobExtensions.EarlyJobInit<TeamManager.AlwaysTeamUpdatePostJob>();
			IJobParallelForTransformExtensions.EarlyJobInit<TransformData.RestoreTransformJob>();
			IJobParallelForTransformExtensions.EarlyJobInit<TransformData.ReadTransformJob>();
			IJobExtensions.EarlyJobInit<TransformManager.EnableTransformJob>();
			IJobParallelForTransformExtensions.EarlyJobInit<TransformManager.RestoreTransformJob>();
			IJobParallelForTransformExtensions.EarlyJobInit<TransformManager.ReadTransformJob>();
			IJobParallelForTransformExtensions.EarlyJobInit<TransformManager.WriteTransformJob>();
			IJobParallelForTransformExtensions.EarlyJobInit<TransformManager.ReadComponentTransformJob>();
			IJobParallelForExtensions.EarlyJobInit<VirtualMeshManager.CalcMeshConvert_A_Job>();
			IJobParallelForExtensions.EarlyJobInit<VirtualMeshManager.CalcMeshConvert_B_Job>();
			IJobParallelForExtensions.EarlyJobInit<VirtualMeshManager.PostRenderMeshWorkDataBatchJob>();
			IJobExtensions.EarlyJobInit<SameDistanceReduction.InitGridJob>();
			IJobExtensions.EarlyJobInit<SameDistanceReduction.SearchJoinJob>();
			IJobExtensions.EarlyJobInit<SameDistanceReduction.JoinJob2>();
			IJobParallelForExtensions.EarlyJobInit<SameDistanceReduction.UpdateJoinIndexJob>();
			IJobParallelForExtensions.EarlyJobInit<SameDistanceReduction.UpdateLinkIndexJob>();
			IJobParallelForExtensions.EarlyJobInit<SameDistanceReduction.FinalMergeVertexJob>();
			IJobExtensions.EarlyJobInit<ShapeDistanceReduction.SearchJoinEdgeJob>();
			IJobExtensions.EarlyJobInit<SimpleDistanceReduction.InitGridJob>();
			IJobExtensions.EarlyJobInit<SimpleDistanceReduction.SearchJoinEdgeJob>();
			IJobExtensions.EarlyJobInit<StepReductionBase.DeterminJoinEdgeJob>();
			IJobExtensions.EarlyJobInit<StepReductionBase.JoinPairJob>();
			IJobParallelForExtensions.EarlyJobInit<StepReductionBase.UpdateJoinIndexJob>();
			IJobParallelForExtensions.EarlyJobInit<StepReductionBase.UpdateLinkIndexJob>();
			IJobParallelForExtensions.EarlyJobInit<StepReductionBase.FinalMergeVertexJob>();
			IJobParallelForExtensions.EarlyJobInit<JobUtility.SerialNumberJob>();
			IJobExtensions.EarlyJobInit<JobUtility.CalcAABBJob>();
			IJobExtensions.EarlyJobInit<JobUtility.CalcAABBDeferJob>();
			IJobParallelForExtensions.EarlyJobInit<JobUtility.CalcUVJob>();
			IJobParallelForExtensions.EarlyJobInit<JobUtility.AddIntDataCopyJob>();
			IJobParallelForExtensions.EarlyJobInit<JobUtility.AddInt2DataCopyJob>();
			IJobParallelForExtensions.EarlyJobInit<JobUtility.AddInt3DataCopyJob>();
			IJobParallelForExtensions.EarlyJobInit<JobUtility.TransformPositionJob>();
			IJobParallelForExtensions.EarlyJobInit<JobUtility.TransformPositionJob2>();
			IJobExtensions.EarlyJobInit<JobUtility.ClearReferenceJob>();
			IJobParallelForExtensions.EarlyJobInit<VirtualMesh.Import_GenerateTangentJob>();
			IJobParallelForExtensions.EarlyJobInit<VirtualMesh.Import_CalcSkinningJob>();
			IJobExtensions.EarlyJobInit<VirtualMesh.Import_BoneWeightJob1>();
			IJobParallelForExtensions.EarlyJobInit<VirtualMesh.Import_BoneWeightJob2>();
			IJobParallelForExtensions.EarlyJobInit<VirtualMesh.Import_BoneVertexJob>();
			IJobExtensions.EarlyJobInit<VirtualMesh.Select_PackVertexJob>();
			IJobExtensions.EarlyJobInit<VirtualMesh.Select_GridJob>();
			IJobParallelForExtensions.EarlyJobInit<VirtualMesh.Add_CalcBindPoseJob>();
			IJobParallelForExtensions.EarlyJobInit<VirtualMesh.Add_CopyVerticesJob>();
			IJobExtensions.EarlyJobInit<VirtualMesh.Mapping_DirectConnectionVertexDataJob>();
			IJobExtensions.EarlyJobInit<VirtualMesh.Mapping_CalcDirectWeightJob>();
			IJobExtensions.EarlyJobInit<VirtualMesh.Mapping_CalcConnectionVertexDataJob>();
			IJobParallelForExtensions.EarlyJobInit<VirtualMesh.Mapping_CalcWeightJob>();
			IJobExtensions.EarlyJobInit<VirtualMesh.Optimize_EdgeToTrianlgeJob>();
			IJobParallelForExtensions.EarlyJobInit<VirtualMesh.ProxyNormalRadiationAdjustmentJob>();
			IJobExtensions.EarlyJobInit<VirtualMesh.ProxyCreateFixedListAndAABBJob>();
			IJobParallelForExtensions.EarlyJobInit<VirtualMesh.Proxy_CalcTriangleNormalJob>();
			IJobParallelForExtensions.EarlyJobInit<VirtualMesh.Proxy_CalcTriangleTangentJob>();
			IJobExtensions.EarlyJobInit<VirtualMesh.Proxy_CreateVertexToTrianglesJob>();
			IJobParallelForExtensions.EarlyJobInit<VirtualMesh.Proxy_OrganizeVertexToTrianglsJob>();
			IJobParallelForExtensions.EarlyJobInit<VirtualMesh.Proxy_CalcVertexNormalTangentFromTriangleJob>();
			IJobParallelForExtensions.EarlyJobInit<VirtualMesh.Proxy_CalcVertexToTransformJob>();
			IJobExtensions.EarlyJobInit<VirtualMesh.Proxy_CalcEdgeToTriangleJob>();
			IJobParallelForExtensions.EarlyJobInit<VirtualMesh.Proxy_CalcVertexBindPoseJob2>();
			IJobExtensions.EarlyJobInit<VirtualMesh.Proxy_CalcVertexToVertexFromTriangleJob>();
			IJobExtensions.EarlyJobInit<VirtualMesh.Proxy_CalcVertexToVertexFromLineJob>();
			IJobParallelForExtensions.EarlyJobInit<VirtualMesh.Proxy_CreateEdgeFlagJob>();
			IJobParallelForExtensions.EarlyJobInit<VirtualMesh.Proxy_CalcCustomSkinningWeightsJobV2>();
			IJobParallelForExtensions.EarlyJobInit<VirtualMesh.Proxy_ApplySelectionJob>();
			IJobParallelForExtensions.EarlyJobInit<VirtualMesh.Proxy_BoneClothApplayTransformFlagJob>();
			IJobExtensions.EarlyJobInit<VirtualMesh.BaseLine_Mesh_CreateParentJob2>();
			IJobExtensions.EarlyJobInit<VirtualMesh.BaseLine_Mesh_CareteFixedListJob>();
			IJobExtensions.EarlyJobInit<VirtualMesh.BaseLine_Bone_CreateBoneChildInfoJob>();
			IJobParallelForExtensions.EarlyJobInit<VirtualMesh.BaseLine_CalcLocalPositionRotationJob>();
			IJobExtensions.EarlyJobInit<VirtualMesh.BaseLine_CalcMaxBaseLineLengthJob>();
			IJobExtensions.EarlyJobInit<VirtualMesh.Reduction_InitVertexToVertexJob2>();
			IJobExtensions.EarlyJobInit<VirtualMesh.Organize_RemapVertexJob>();
			IJobExtensions.EarlyJobInit<VirtualMesh.Organize_CollectUseSkinBoneJob>();
			IJobParallelForExtensions.EarlyJobInit<VirtualMesh.Organize_CopyVertexJob>();
			IJobParallelForExtensions.EarlyJobInit<VirtualMesh.Organize_RemapBoneWeightJob>();
			IJobParallelForExtensions.EarlyJobInit<VirtualMesh.Organize_RemapLinkPointArrayJob>();
			IJobExtensions.EarlyJobInit<VirtualMesh.Organize_CreateLineTriangleJob>();
			IJobExtensions.EarlyJobInit<VirtualMesh.Organize_CreateLineTriangleJob2>();
			IJobExtensions.EarlyJobInit<VirtualMesh.Organize_CreateNewTriangleJob3>();
			IJobExtensions.EarlyJobInit<VirtualMesh.Work_AverageTriangleDistanceJob>();
			IJobExtensions.EarlyJobInit<VirtualMesh.Work_AverageLineDistanceJob>();
			IJobExtensions.EarlyJobInit<VirtualMesh.Work_AddVertexIndexGirdMapJob>();
			IJobParallelForExtensions.EarlyJobInit<VirtualMesh.Work_IntersectTriangleJob>();
			IJobParallelForExtensions.EarlyJobInit<VirtualMesh.Work_IntersectEdgeJob>();
			IJobParallelForExtensions.EarlyJobInit<VirtualMesh.Work_IntersectPointJob>();
			IJobExtensions.EarlyJobInit<VirtualMesh.Work_IntersetcSortJob>();
			IJobParallelForExtensions.EarlyJobInit<JobUtility.FillJob<int>>();
			IJobParallelForExtensions.EarlyJobInit<JobUtility.FillJob<Vector4>>();
			IJobParallelForExtensions.EarlyJobInit<JobUtility.FillJob<VirtualMeshBoneWeight>>();
			IJobParallelForExtensions.EarlyJobInit<JobUtility.FillJob<byte>>();
			IJobParallelForExtensions.EarlyJobInit<JobUtility.FillJob<quaternion>>();
			IJobParallelForExtensions.EarlyJobInit<JobUtility.FillJob2<int>>();
			IJobExtensions.EarlyJobInit<JobUtility.FillRefJob<int>>();
			IJobExtensions.EarlyJobInit<JobUtility.ConvertHashSetToListJob<int>>();
			IJobExtensions.EarlyJobInit<JobUtility.ConvertHashSetKeyToListJob<int2>>();
			IJobExtensions.EarlyJobInit<JobUtility.ConvertHashSetKeyToListJob<int4>>();
			IJobExtensions.EarlyJobInit<JobUtility.ConvertArrayToMapJob<ushort>>();
			IJobExtensions.EarlyJobInit<NativeMultiHashMapExtensions.SetParallelMultiHashMapJob<int2, ushort>>();
		}
		catch (Exception ex)
		{
			EarlyInitHelpers.JobReflectionDataCreationFailed(ex);
		}
	}

	[RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterAssembliesLoaded)]
	public static void EarlyInit()
	{
		CreateJobReflectionData();
	}
}
