public static class AchievementIds
{
	public const string DEMO_ACHIEVEMENT_TOKEN_COLLECTOR = "ACHIEVEMENT_TOKEN_COLLECTOR";

	public const string DEMO_ACHIEVEMENT_FIRST_ESCAPE = "ACHIEVEMENT_FIRST_ESCAPE";

	public const string DEMO_ACHIEVEMENT_PUZZLE_MASTER = "ACHIEVEMENT_PUZZLE_MASTER";

	public const string DEMO_ACHIEVEMENT_JIGSAW_ARTIST = "ACHIEVEMENT_JIGSAW_ARTIST";

	public const string ACHIEVEMENT_FINISH_ROOM = "ACHIEVEMENT_FINISH_ROOM";

	public const string ACHIEVEMENT_FINISH_ROOM_MP = "ACHIEVEMENT_FINISH_ROOM_MP";

	public const string ACHIEVEMENT_FIND_TOKEN = "ACHIEVEMENT_FIND_TOKEN";

	public const string ACHIEVEMENT_FIND_ALL_TOKENS_PACK = "ACHIEVEMENT_FIND_ALL_TOKENS_PACK";

	public const string ACHIEVEMENT_FIND_ALL_TOKENS_GAME = "ACHIEVEMENT_FIND_ALL_TOKENS_GAME";

	public const string ACHIEVEMENT_GET_TROPHY = "ACHIEVEMENT_GET_TROPHY";

	public const string ACHIEVEMENT_GET_ALL_TROPHIES_PACK = "ACHIEVEMENT_GET_ALL_TROPHIES_PACK";

	public const string ACHIEVEMENT_GET_ALL_TROPHIES_GAME = "ACHIEVEMENT_GET_ALL_TROPHIES_GAME";

	public const string ACHIEVEMENT_FINISH_DARKEST_ROOM = "ACHIEVEMENT_FINISH_DARKEST";

	public const string ACHIEVEMENT_FINISH_ALL_DARKEST_ROOMS = "ACHIEVEMENT_FINISH_ALL_DARKEST_ROOMS";

	public const string ACHIEVEMENT_FINISH_COMMUNITY_ROOM = "ACHIEVEMENT_FINISH_COMMUNITY_ROOM";

	public const string ACHIEVEMENT_EAT_FOOD = "ACHIEVEMENT_EAT_FOOD";

	public const string ACHIEVEMENT_CHARACTER_CUSTOMIZED = "ACHIEVEMENT_CHARACTER_CUSTOMIZED";

	public const string ACHIEVEMENT_CALL_A_FRIEND = "ACHIEVEMENT_CALL_A_FRIEND";

	public const string ACHIEVEMENT_JUST_DANCE = "ACHIEVEMENT_JUST_DANCE";

	public const string ACHIEVEMENT_LOOK_LOOK_LOOK = "ACHIEVEMENT_LOOK_LOOK_LOOK";

	public const string ACHIEVEMENT_READ_A_COMIC = "ACHIEVEMENT_READ_A_COMIC";

	public const string ACHIEVEMENT_RELAX = "ACHIEVEMENT_RELAX";

	public const string ACHIEVEMENT_BUILDER = "ACHIEVEMENT_BUILDER";

	public const string ACHIEVEMENT_GOOD_THROW = "ACHIEVEMENT_GOOD_THROW";

	public const string ACHIEVEMENT_CLEANER = "ACHIEVEMENT_CLEANER";

	public const string ACHIEVEMENT_POCKETS_WITH_HOLES = "ACHIEVEMENT_POCKETS_WITH_HOLES";

	public const string ACHIEVEMENT_PREMIUM_LOOK = "ACHIEVEMENT_PREMIUM_LOOK";

	public const string ACHIEVEMENT_TAKE_A_HINT = "ACHIEVEMENT_TAKE_A_HINT";

	public const string ACHIEVEMENT_BURN_LOG = "ACHIEVEMENT_BURN_LOG";

	public const string ACHIEVEMENT_D3_POWER_NAP = "ACHIEVEMENT_D3_POWER_NAP";
}
