using UnityEngine;
using UnityEngine.UI;

public class PublishInfoUI : PineUIComponent
{
	public RectTransform root;

	public Image Publish;

	public Image Publish_Title;

	public Text Publish_Title_Text;

	public Image Publish_Description;

	public Image Publish_Description_BotBorder;

	public Image Publish_Description_DescriptionTabs;

	public Button Publish_Description_DescriptionTabs_BasicInformation;

	public Text Publish_Description_DescriptionTabs_BasicInformation_Text;

	public Image Publish_Description_DescriptionTabs_BasicInformation_Selected;

	public Button Publish_Description_DescriptionTabs_TagsButton;

	public Text Publish_Description_DescriptionTabs_TagsButton_Text;

	public Image Publish_Description_DescriptionTabs_TagsButton_Selected;

	public InputField Publish_Description_BasicInformationContent;

	public Image Publish_Description_BasicInformationContent_Level;

	public RawImage Publish_Description_BasicInformationContent_Level_LevelImage;

	public Button Publish_Description_BasicInformationContent_Level_ScreenshotButton;

	public Image Publish_Description_BasicInformationContent_Level_ScreenshotButton_Icon;

	public Image Publish_Description_BasicInformationContent_Layout_Name;

	public Text Publish_Description_BasicInformationContent_Layout_Name_Title;

	public InputField Publish_Description_BasicInformationContent_Layout_Name_InputField;

	public Text Publish_Description_BasicInformationContent_Layout_Name_InputField_LevelName;

	public Button Publish_Description_BasicInformationContent_Layout_Name_IDBtn;

	public Text Publish_Description_BasicInformationContent_Layout_Name_IDBtn_Text;

	public CanvasGroup Publish_Description_BasicInformationContent_Layout_DifficultyDropdown;

	public Text Publish_Description_BasicInformationContent_Layout_DifficultyDropdown_Title;

	public Dropdown Publish_Description_BasicInformationContent_Layout_DifficultyDropdown_Dropdown;

	public Text Publish_Description_BasicInformationContent_Layout_DifficultyDropdown_Dropdown_Label;

	public Image Publish_Description_BasicInformationContent_Layout_DifficultyDropdown_Dropdown_Label_newIcon;

	public Image Publish_Description_BasicInformationContent_Layout_DifficultyDropdown_Dropdown_Label_BGArrow_Arrow;

	public Image Publish_Description_BasicInformationContent_Layout_DifficultyDropdown_Dropdown_Template;

	public Image Publish_Description_BasicInformationContent_Layout_DifficultyDropdown_Dropdown_Template_Viewport;

	public Image Publish_Description_BasicInformationContent_Layout_DifficultyDropdown_Dropdown_Template_Viewport_Content;

	public Image Publish_Description_BasicInformationContent_Layout_DifficultyDropdown_Dropdown_Template_Viewport_Content_Item_ItemBackground;

	public Image Publish_Description_BasicInformationContent_Layout_DifficultyDropdown_Dropdown_Template_Viewport_Content_Item_ItemCheckmark;

	public Text Publish_Description_BasicInformationContent_Layout_DifficultyDropdown_Dropdown_Template_Viewport_Content_Item_ItemLabel;

	public Image Publish_Description_BasicInformationContent_Layout_DifficultyDropdown_Dropdown_Template_Viewport_Content_Item_ItemLabel_Image;

	public Image Publish_Description_BasicInformationContent_Layout_DifficultyDropdown_Dropdown_Template_ES2ScrollbarVertical;

	public Image Publish_Description_BasicInformationContent_Layout_DifficultyDropdown_Dropdown_Template_ES2ScrollbarVertical_BGImage;

	public Image Publish_Description_BasicInformationContent_Layout_DifficultyDropdown_Dropdown_Template_ES2ScrollbarVertical_SlidingArea_Handle;

	public Image Publish_Description_BasicInformationContent_Layout_DifficultyDropdown_Dropdown_Template_ES2ScrollbarVertical_SlidingArea_Handle_BGHandle;

	public CanvasGroup Publish_Description_BasicInformationContent_Layout_PlayTimeDropdown;

	public Text Publish_Description_BasicInformationContent_Layout_PlayTimeDropdown_Title;

	public Dropdown Publish_Description_BasicInformationContent_Layout_PlayTimeDropdown_Dropdown;

	public Text Publish_Description_BasicInformationContent_Layout_PlayTimeDropdown_Dropdown_Label;

	public Image Publish_Description_BasicInformationContent_Layout_PlayTimeDropdown_Dropdown_Label_newIcon;

	public Image Publish_Description_BasicInformationContent_Layout_PlayTimeDropdown_Dropdown_Label_BGArrow_Arrow;

	public Image Publish_Description_BasicInformationContent_Layout_PlayTimeDropdown_Dropdown_Template;

	public Image Publish_Description_BasicInformationContent_Layout_PlayTimeDropdown_Dropdown_Template_Viewport;

	public Image Publish_Description_BasicInformationContent_Layout_PlayTimeDropdown_Dropdown_Template_Viewport_Content;

	public Image Publish_Description_BasicInformationContent_Layout_PlayTimeDropdown_Dropdown_Template_Viewport_Content_Item_ItemBackground;

	public Image Publish_Description_BasicInformationContent_Layout_PlayTimeDropdown_Dropdown_Template_Viewport_Content_Item_ItemCheckmark;

	public Text Publish_Description_BasicInformationContent_Layout_PlayTimeDropdown_Dropdown_Template_Viewport_Content_Item_ItemLabel;

	public Image Publish_Description_BasicInformationContent_Layout_PlayTimeDropdown_Dropdown_Template_Viewport_Content_Item_ItemLabel_Image;

	public Image Publish_Description_BasicInformationContent_Layout_PlayTimeDropdown_Dropdown_Template_ES2ScrollbarVertical;

	public Image Publish_Description_BasicInformationContent_Layout_PlayTimeDropdown_Dropdown_Template_ES2ScrollbarVertical_BGImage;

	public Image Publish_Description_BasicInformationContent_Layout_PlayTimeDropdown_Dropdown_Template_ES2ScrollbarVertical_SlidingArea_Handle;

	public Image Publish_Description_BasicInformationContent_Layout_PlayTimeDropdown_Dropdown_Template_ES2ScrollbarVertical_SlidingArea_Handle_BGHandle;

	public CanvasGroup Publish_Description_BasicInformationContent_Layout_NumOfPlayersDropdownMin;

	public Text Publish_Description_BasicInformationContent_Layout_NumOfPlayersDropdownMin_Title;

	public Dropdown Publish_Description_BasicInformationContent_Layout_NumOfPlayersDropdownMin_Min;

	public Text Publish_Description_BasicInformationContent_Layout_NumOfPlayersDropdownMin_Min_Label;

	public Image Publish_Description_BasicInformationContent_Layout_NumOfPlayersDropdownMin_Min_Label_newIcon;

	public Image Publish_Description_BasicInformationContent_Layout_NumOfPlayersDropdownMin_Min_Label_BGArrow_Arrow;

	public Image Publish_Description_BasicInformationContent_Layout_NumOfPlayersDropdownMin_Min_Template;

	public Image Publish_Description_BasicInformationContent_Layout_NumOfPlayersDropdownMin_Min_Template_Viewport;

	public Image Publish_Description_BasicInformationContent_Layout_NumOfPlayersDropdownMin_Min_Template_Viewport_Content;

	public Image Publish_Description_BasicInformationContent_Layout_NumOfPlayersDropdownMin_Min_Template_Viewport_Content_Item_ItemBackground;

	public Image Publish_Description_BasicInformationContent_Layout_NumOfPlayersDropdownMin_Min_Template_Viewport_Content_Item_ItemCheckmark;

	public Text Publish_Description_BasicInformationContent_Layout_NumOfPlayersDropdownMin_Min_Template_Viewport_Content_Item_ItemLabel;

	public Image Publish_Description_BasicInformationContent_Layout_NumOfPlayersDropdownMin_Min_Template_Viewport_Content_Item_ItemLabel_Image;

	public Image Publish_Description_BasicInformationContent_Layout_NumOfPlayersDropdownMin_Min_Template_ES2ScrollbarVertical;

	public Image Publish_Description_BasicInformationContent_Layout_NumOfPlayersDropdownMin_Min_Template_ES2ScrollbarVertical_BGImage;

	public Image Publish_Description_BasicInformationContent_Layout_NumOfPlayersDropdownMin_Min_Template_ES2ScrollbarVertical_SlidingArea_Handle;

	public Image Publish_Description_BasicInformationContent_Layout_NumOfPlayersDropdownMin_Min_Template_ES2ScrollbarVertical_SlidingArea_Handle_BGHandle;

	public CanvasGroup Publish_Description_BasicInformationContent_Layout_NumOfPlayersDropdownMax;

	public Text Publish_Description_BasicInformationContent_Layout_NumOfPlayersDropdownMax_Title;

	public Dropdown Publish_Description_BasicInformationContent_Layout_NumOfPlayersDropdownMax_Max;

	public Text Publish_Description_BasicInformationContent_Layout_NumOfPlayersDropdownMax_Max_Label;

	public Image Publish_Description_BasicInformationContent_Layout_NumOfPlayersDropdownMax_Max_Label_newIcon;

	public Image Publish_Description_BasicInformationContent_Layout_NumOfPlayersDropdownMax_Max_Label_BGArrow_Arrow;

	public Image Publish_Description_BasicInformationContent_Layout_NumOfPlayersDropdownMax_Max_Template;

	public Image Publish_Description_BasicInformationContent_Layout_NumOfPlayersDropdownMax_Max_Template_Viewport;

	public Image Publish_Description_BasicInformationContent_Layout_NumOfPlayersDropdownMax_Max_Template_Viewport_Content;

	public Image Publish_Description_BasicInformationContent_Layout_NumOfPlayersDropdownMax_Max_Template_Viewport_Content_Item_ItemBackground;

	public Image Publish_Description_BasicInformationContent_Layout_NumOfPlayersDropdownMax_Max_Template_Viewport_Content_Item_ItemCheckmark;

	public Text Publish_Description_BasicInformationContent_Layout_NumOfPlayersDropdownMax_Max_Template_Viewport_Content_Item_ItemLabel;

	public Image Publish_Description_BasicInformationContent_Layout_NumOfPlayersDropdownMax_Max_Template_Viewport_Content_Item_ItemLabel_Image;

	public Image Publish_Description_BasicInformationContent_Layout_NumOfPlayersDropdownMax_Max_Template_ES2ScrollbarVertical;

	public Image Publish_Description_BasicInformationContent_Layout_NumOfPlayersDropdownMax_Max_Template_ES2ScrollbarVertical_BGImage;

	public Image Publish_Description_BasicInformationContent_Layout_NumOfPlayersDropdownMax_Max_Template_ES2ScrollbarVertical_SlidingArea_Handle;

	public Image Publish_Description_BasicInformationContent_Layout_NumOfPlayersDropdownMax_Max_Template_ES2ScrollbarVertical_SlidingArea_Handle_BGHandle;

	public Text Publish_Description_BasicInformationContent_Description;

	public InputField Publish_Description_BasicInformationContent_DescriptionInput;

	public Text Publish_Description_BasicInformationContent_DescriptionInput_Text;

	public Text Publish_Description_BasicInformationContent_Label;

	public InputField Publish_Description_BasicInformationContent_PatchInput;

	public Text Publish_Description_BasicInformationContent_PatchInput_Text;

	public InputField Publish_Description_TagsContent;

	public Image Publish_Description_TagsContent_Background;

	public Image Publish_Description_TagsContent_Background_ScrollView;

	public Image Publish_Description_TagsContent_Background_ScrollView_Viewport;

	public RectTransform Publish_Description_TagsContent_Background_ScrollView_Viewport_PublishingInfoWorkshopTags;

	public Toggle Publish_Description_TagsContent_Background_ScrollView_Viewport_ToggleTemplate;

	public Image Publish_Description_TagsContent_Background_ScrollView_Viewport_ToggleTemplate_Background;

	public Image Publish_Description_TagsContent_Background_ScrollView_Viewport_ToggleTemplate_Background_Checked;

	public Text Publish_Description_TagsContent_Background_ScrollView_Viewport_ToggleTemplate_Label;

	public Text Publish_Description_TagsContent_Background_ScrollView_Viewport_CategorySpacerTemplate;

	public Image Publish_Description_TagsContent_Background_ScrollView_ScrollbarVertical;

	public Image Publish_Description_TagsContent_Background_ScrollView_ScrollbarVertical_SlidingArea_Handle;

	public Image Publish_Footer;

	public CanvasGroup Publish_Footer_VisibilityDropdown;

	public Text Publish_Footer_VisibilityDropdown_Title;

	public Dropdown Publish_Footer_VisibilityDropdown_Dropdown;

	public Text Publish_Footer_VisibilityDropdown_Dropdown_Label;

	public Image Publish_Footer_VisibilityDropdown_Dropdown_Label_newIcon;

	public Image Publish_Footer_VisibilityDropdown_Dropdown_Label_BGArrow_Arrow;

	public Image Publish_Footer_VisibilityDropdown_Dropdown_Template;

	public Image Publish_Footer_VisibilityDropdown_Dropdown_Template_Viewport;

	public Image Publish_Footer_VisibilityDropdown_Dropdown_Template_Viewport_Content;

	public Image Publish_Footer_VisibilityDropdown_Dropdown_Template_Viewport_Content_Item_ItemBackground;

	public Image Publish_Footer_VisibilityDropdown_Dropdown_Template_Viewport_Content_Item_ItemCheckmark;

	public Text Publish_Footer_VisibilityDropdown_Dropdown_Template_Viewport_Content_Item_ItemLabel;

	public Image Publish_Footer_VisibilityDropdown_Dropdown_Template_Viewport_Content_Item_ItemLabel_Image;

	public Image Publish_Footer_VisibilityDropdown_Dropdown_Template_ES2ScrollbarVertical;

	public Image Publish_Footer_VisibilityDropdown_Dropdown_Template_ES2ScrollbarVertical_BGImage;

	public Image Publish_Footer_VisibilityDropdown_Dropdown_Template_ES2ScrollbarVertical_SlidingArea_Handle;

	public Image Publish_Footer_VisibilityDropdown_Dropdown_Template_ES2ScrollbarVertical_SlidingArea_Handle_BGHandle;

	public Button Publish_Footer_PublishButton;

	public Text Publish_Footer_PublishButton_Text;

	public Button Publish_Footer_CancelButton;

	public Text Publish_Footer_CancelButton_Text;

	public Image PublishingWaiting;

	public Text PublishingWaiting_Text;

	public Image PublishingWaiting_Image;

	public Button PublishingWaiting_Error;

	public Image PublishingWaiting_Error_Background;

	public Text PublishingWaiting_Error_Background_error;

	public Text PublishingWaiting_Error_Background_errorLbl;

	public Button PublishingWaiting_Error_Background_Cancel;

	public Text PublishingWaiting_Error_Background_Cancel_Text;

	public Image SaveOnExitModal;

	public Button SaveOnExitModal_buttons_no;

	public Text SaveOnExitModal_buttons_no_Text;

	public Button SaveOnExitModal_buttons_yes;

	public Text SaveOnExitModal_buttons_yes_Text;

	public Image EditID;

	public InputField EditID_IDInputField;

	public Text EditID_IDInputField_ID;

	public Text EditID_Error;

	public Text EditID_Intro;

	public Button EditID_buttons_cancel;

	public Text EditID_buttons_cancel_Text;

	public Button EditID_buttons_save;

	public Text EditID_buttons_save_Text;

	public object data;

	private bool isInitialized;

	protected override void Awake()
	{
		init();
	}

	public void init()
	{
		if (!isInitialized)
		{
			isInitialized = true;
			PineUI.addButtonListeners(Publish_Description_DescriptionTabs_BasicInformation);
			PineUI.addButtonListeners(Publish_Description_DescriptionTabs_TagsButton);
			PineUI.addButtonListeners(Publish_Description_BasicInformationContent_Level_ScreenshotButton);
			PineUI.addButtonListeners(Publish_Description_BasicInformationContent_Layout_Name_IDBtn);
			PineUI.addDropdownListeners(Publish_Description_BasicInformationContent_Layout_DifficultyDropdown_Dropdown);
			PineUI.addDropdownListeners(Publish_Description_BasicInformationContent_Layout_PlayTimeDropdown_Dropdown);
			PineUI.addDropdownListeners(Publish_Description_BasicInformationContent_Layout_NumOfPlayersDropdownMin_Min);
			PineUI.addDropdownListeners(Publish_Description_BasicInformationContent_Layout_NumOfPlayersDropdownMax_Max);
			PineUI.addToggleListeners(Publish_Description_TagsContent_Background_ScrollView_Viewport_ToggleTemplate);
			PineUI.addDropdownListeners(Publish_Footer_VisibilityDropdown_Dropdown);
			PineUI.addButtonListeners(Publish_Footer_PublishButton);
			PineUI.addButtonListeners(Publish_Footer_CancelButton);
			PineUI.addButtonListeners(PublishingWaiting_Error);
			PineUI.addButtonListeners(PublishingWaiting_Error_Background_Cancel);
			PineUI.addButtonListeners(SaveOnExitModal_buttons_no);
			PineUI.addButtonListeners(SaveOnExitModal_buttons_yes);
			PineUI.addButtonListeners(EditID_buttons_cancel);
			PineUI.addButtonListeners(EditID_buttons_save);
		}
	}
}
