<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Assembly-CSharp</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>Exe</OutputType>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="com.rlabrecque.steamworks.net">
      <HintPath>..\..\IronNest\com.rlabrecque.steamworks.net.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\IronNest\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="System.Net.Http" />
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>..\..\IronNest\UnityEngine.AnimationModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.InputSystem">
      <HintPath>..\..\IronNest\Unity.InputSystem.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>..\..\IronNest\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.AI.Navigation">
      <HintPath>..\..\IronNest\Unity.AI.Navigation.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>..\..\IronNest\UnityEngine.UIModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>..\..\IronNest\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="Heathen.Steamworks">
      <HintPath>..\..\IronNest\Heathen.Steamworks.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>..\..\IronNest\UnityEngine.AudioModule.dll</HintPath>
    </Reference>
    <Reference Include="System.Core">
      <HintPath>..\..\IronNest\System.Core.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\..\IronNest\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.Physics2DModule">
      <HintPath>..\..\IronNest\UnityEngine.Physics2DModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>..\..\IronNest\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="Unity.RenderPipelines.Universal.Runtime">
      <HintPath>..\..\IronNest\Unity.RenderPipelines.Universal.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="System.IO.Compression" />
    <Reference Include="Unity.RenderPipelines.Core.Runtime">
      <HintPath>..\..\IronNest\Unity.RenderPipelines.Core.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Cinemachine">
      <HintPath>..\..\IronNest\Unity.Cinemachine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AIModule">
      <HintPath>..\..\IronNest\UnityEngine.AIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>..\..\IronNest\UnityEngine.ParticleSystemModule.dll</HintPath>
    </Reference>
    <Reference Include="FMODUnity">
      <HintPath>..\..\IronNest\FMODUnity.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VideoModule">
      <HintPath>..\..\IronNest\UnityEngine.VideoModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Services.Analytics">
      <HintPath>..\..\IronNest\Unity.Services.Analytics.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestModule">
      <HintPath>..\..\IronNest\UnityEngine.UnityWebRequestModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIElementsModule">
      <HintPath>..\..\IronNest\UnityEngine.UIElementsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>..\..\IronNest\UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>..\..\IronNest\UnityEngine.ImageConversionModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>..\..\IronNest\UnityEngine.IMGUIModule.dll</HintPath>
    </Reference>
    <Reference Include="HTraceAO">
      <HintPath>..\..\IronNest\HTraceAO.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Services.Core">
      <HintPath>..\..\IronNest\Unity.Services.Core.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Services.Core.Environments">
      <HintPath>..\..\IronNest\Unity.Services.Core.Environments.dll</HintPath>
    </Reference>
    <ProjectReference Include="..\Assembly-CSharp-firstpass\Assembly-CSharp-firstpass.csproj" />
    <ProjectReference Include="..\Kamgam.SettingsGenerator\Kamgam.SettingsGenerator.csproj" />
    <ProjectReference Include="..\ShapesRuntime\ShapesRuntime.csproj" />
    <ProjectReference Include="..\Kamgam.UGUIComponentsForSettings\Kamgam.UGUIComponentsForSettings.csproj" />
  </ItemGroup>
</Project>