namespace RakNet
{
	public enum UDPForwarderResult
	{
		UDPFORWARDER_FORWARDING_ALREADY_EXISTS = 0,
		UDPFORWARDER_NO_SOCKETS = 1,
		UDPFORWARDER_BIND_FAILED = 2,
		UDPFORWARDER_INVALID_PARAMETERS = 3,
		UDPFORWARDER_NOT_RUNNING = 4,
		UDPFORWARDER_SUCCESS = 5,
		UDPFORWARDER_RESULT_COUNT = 6
	}
}
