namespace PartyCSharpSDK
{
	public enum PARTY_AUDIO_INPUT_STATE : uint
	{
		PARTY_AUDIO_INPUT_STATE_NO_INPUT = 0u,
		PARTY_AUDIO_INPUT_STATE_INITIALIZED = 1u,
		PARTY_AUDIO_INPUT_STATE_NOT_FOUND = 2u,
		PARTY_AUDIO_INPUT_STATE_USER_CONSENT_DENIED = 3u,
		PARTY_AUDIO_INPUT_STATE_UNSUPPORTED_FORMAT = 4u,
		PARTY_AUDIO_INPUT_STATE_ALREADY_IN_USE = 5u,
		PARTY_AUDIO_INPUT_STATE_UNKNOWN_ERROR = 6u
	}
}
