namespace PartyCSharpSDK
{
	public enum PARTY_VOICE_CHAT_TRANSCRIPTION_PHRASE_TYPE : uint
	{
		PARTY_VOICE_CHAT_TRANSCRIPTION_PHRASE_TYPE_HYPOTHESIS = 0u,
		PARTY_VOICE_CHAT_TRANSCRIPTION_PHRASE_TYPE_FINAL = 1u
	}
}
