namespace PartyCSharpSDK
{
	public enum PARTY_ENDPOINT_STATISTIC : uint
	{
		PARTY_ENDPOINT_STATISTIC_CURRENTLY_QUEUED_SEND_MESSAGES = 0u,
		PARTY_ENDPOINT_STATISTIC_CURRENTLY_QUEUED_SEND_MESSAGE_BYTES = 1u,
		PARTY_ENDPOINT_STATISTIC_CURRENTLY_ACTIVE_SEND_MESSAGES = 2u,
		PARTY_ENDPOINT_STATISTIC_CURRENTLY_ACTIVE_SEND_MESSAGE_BYTES = 3u,
		PARTY_ENDPOINT_STATISTIC_TIMED_OUT_SEND_MESSAGES = 4u,
		PARTY_ENDPOINT_STATISTIC_TIMED_OUT_SEND_MESSAGE_BYTES = 5u,
		PARTY_ENDPOINT_STATISTIC_CANCELED_SEND_MESSAGES = 6u,
		PARTY_ENDPOINT_STATISTIC_CANCELED_SEND_MESSAGE_BYTES = 7u,
		PARTY_ENDPOINT_STATISTIC_AVERAGE_DEVICE_ROUND_TRIP_LATENCY_IN_MILLISECONDS = 8u
	}
}
