namespace PartyCSharpSDK
{
	public enum PARTY_AUDIO_OUTPUT_STATE : uint
	{
		PARTY_AUDIO_OUTPUT_STATE_NO_OUTPUT = 0u,
		PARTY_AUDIO_OUTPUT_STATE_INITIALIZED = 1u,
		PARTY_AUDIO_OUTPUT_STATE_NOT_FOUND = 2u,
		PARTY_AUDIO_OUTPUT_STATE_UNSUPPORTED_FORMAT = 3u,
		PARTY_AUDIO_OUTPUT_STATE_ALREADY_IN_USE = 4u,
		PARTY_AUDIO_OUTPUT_STATE_UNKNOWN_ERROR = 5u
	}
}
