namespace PartyCSharpSDK
{
	public enum PARTY_LOCAL_CHAT_CONTROL_CHAT_INDICATOR : uint
	{
		PARTY_LOCAL_CHAT_CONTROL_CHAT_INDICATOR_SILENT = 0u,
		PARTY_LOCAL_CHAT_CONTROL_CHAT_INDICATOR_TALKING = 1u,
		PARTY_LOCAL_CHAT_CONTROL_CHAT_INDICATOR_AUDIO_INPUT_MUTED = 2u,
		PARTY_LOCAL_CHAT_CONTROL_CHAT_INDICATOR_NO_AUDIO_INPUT = 3u
	}
}
