namespace PartyCSharpSDK
{
	public enum PARTY_DESTROYED_REASON : uint
	{
		PARTY_DESTROYED_REASON_REQUESTED = 0u,
		PARTY_DESTROYED_REASON_DISCONNECTED = 1u,
		PARTY_DESTROYED_REASON_KICKED = 2u,
		PARTY_DESTROYED_REASON_DEVICE_LOST_AUTHENTICATION = 3u,
		PARTY_DESTROYED_REASON_CREATION_FAILED = 4u
	}
}
