namespace PartyCSharpSDK
{
	public enum PARTY_CHAT_CONTROL_CHAT_INDICATOR : uint
	{
		PARTY_CHAT_CONTROL_CHAT_INDICATOR_SILENT = 0u,
		PARTY_CHAT_CONTROL_CHAT_INDICATOR_TALKING = 1u,
		PARTY_CHAT_CONTROL_CHAT_INDICATOR_INCOMING_VOICE_DISABLED = 2u,
		PARTY_CHAT_CONTROL_CHAT_INDICATOR_INCOMING_COMMUNICATIONS_MUTED = 3u
	}
}
