namespace PartyCSharpSDK
{
	public enum PARTY_LOCAL_UDP_SOCKET_BIND_ADDRESS_OPTIONS : uint
	{
		PARTY_LOCAL_UDP_SOCKET_BIND_ADDRESS_OPTIONS_NONE = 0u,
		PARTY_LOCAL_UDP_SOCKET_BIND_ADDRESS_OPTIONS_EXCLUDE_GAME_CORE_PREFERRED_UDP_MULTIPLAYER_PORT = 1u
	}
}
