namespace PartyCSharpSDK
{
	public enum PARTY_LOCAL_USER_REMOVED_REASON : uint
	{
		PARTY_LOCAL_USER_REMOVED_REASON_AUTHENTICATION_FAILED = 0u,
		PARTY_LOCAL_USER_REMOVED_REASON_REMOVE_LOCAL_USER = 1u,
		PARTY_LOCAL_USER_REMOVED_REASON_DESTROY_LOCAL_USER = 2u,
		PARTY_LOCAL_USER_REMOVED_REASON_DESTROY_NETWORK = 3u
	}
}
