namespace PartyCSharpSDK
{
	public enum PARTY_NETWORK_STATISTIC : uint
	{
		PARTY_NETWORK_STATISTIC_AVERAGE_RELAY_SERVER_ROUND_TRIP_LATENCY_IN_MILLISECONDS = 0u,
		PARTY_NETWORK_STATISTIC_SENT_PROTOCOL_PACKETS = 1u,
		PARTY_NETWORK_STATISTIC_SENT_PROTOCOL_BYTES = 2u,
		PARTY_NETWORK_STATISTIC_RETRIED_PROTOCOL_PACKETS = 3u,
		PARTY_NETWORK_STATISTIC_RETRIED_PROTOCOL_BYTES = 4u,
		PARTY_NETWORK_STATISTIC_DROPPED_PROTOCOL_PACKETS = 5u,
		PARTY_NETWORK_STATISTIC_RECEIVED_PROTOCOL_PACKETS = 6u,
		PARTY_NETWORK_STATISTIC_RECEIVED_PROTOCOL_BYTES = 7u,
		PARTY_NETWORK_STATISTIC_CURRENTLY_QUEUED_SEND_MESSAGES = 8u,
		PARTY_NETWORK_STATISTIC_CURRENTLY_QUEUED_SEND_MESSAGE_BYTES = 9u,
		PARTY_NETWORK_STATISTIC_CURRENTLY_ACTIVE_SEND_MESSAGES = 10u,
		PARTY_NETWORK_STATISTIC_CURRENTLY_ACTIVE_SEND_MESSAGE_BYTES = 11u,
		PARTY_NETWORK_STATISTIC_TIMED_OUT_SEND_MESSAGES = 12u,
		PARTY_NETWORK_STATISTIC_TIMED_OUT_SEND_MESSAGE_BYTES = 13u,
		PARTY_NETWORK_STATISTIC_CANCELED_SEND_MESSAGES = 14u,
		PARTY_NETWORK_STATISTIC_CANCELED_SEND_MESSAGE_BYTES = 15u
	}
}
