namespace PartyCSharpSDK
{
	public enum PARTY_AUDIO_DEVICE_SELECTION_TYPE : uint
	{
		PARTY_AUDIO_DEVICE_SELECTION_TYPE_NONE = 0u,
		PARTY_AUDIO_DEVICE_SELECTION_TYPE_SYSTEM_DEFAULT = 1u,
		PARTY_AUDIO_DEVICE_SELECTION_TYPE_PLATFORM_USER_DEFAULT = 2u,
		PARTY_AUDIO_DEVICE_SELECTION_TYPE_MANUAL = 3u
	}
}
