<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Kamgam.SettingsGeneratorExamples</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>Exe</OutputType>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>..\..\IronNest\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\IronNest\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.InputSystem">
      <HintPath>..\..\IronNest\Unity.InputSystem.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>..\..\IronNest\UnityEngine.AudioModule.dll</HintPath>
    </Reference>
    <Reference Include="LocalizationsForSettings">
      <HintPath>..\..\IronNest\LocalizationsForSettings.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>..\..\IronNest\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIElementsModule">
      <HintPath>..\..\IronNest\UnityEngine.UIElementsModule.dll</HintPath>
    </Reference>
    <ProjectReference Include="..\Kamgam.SettingsGenerator\Kamgam.SettingsGenerator.csproj" />
  </ItemGroup>
</Project>