using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.Versioning;
using UnityEngine.Scripting;

[assembly: InternalsVisibleTo("BitCode.Platform.WindowsGameCore")]
[assembly: InternalsVisibleTo("BitCode.Platform.iOS")]
[assembly: InternalsVisibleTo("BitCode.Editor.L10n")]
[assembly: InternalsVisibleTo("BitCode.L10n")]
[assembly: InternalsVisibleTo("BitCode.Platform.NGP.Android")]
[assembly: InternalsVisibleTo("BitCode.Platform.GameCore")]
[assembly: InternalsVisibleTo("BitCode.Platform.Steamworks")]
[assembly: InternalsVisibleTo("BitCode.Platform.NGP.iOS")]
[assembly: InternalsVisibleTo("BitCode.Platform.NGP")]
[assembly: InternalsVisibleTo("BitCode.IOC")]
[assembly: AssemblyCopyright("Copyright © 24 Bit Games 2023")]
[assembly: AssemblyConfiguration("Release")]
[assembly: AssemblyFileVersion("27.0.0.3625")]
[assembly: AssemblyInformationalVersion("27.0.0+3625.TABS-Development.Unity2019")]
[assembly: InternalsVisibleTo("BitCode.Debug")]
[assembly: InternalsVisibleTo("BitCode.Logging")]
[assembly: InternalsVisibleTo("BitCode.Tests")]
[assembly: InternalsVisibleTo("BitCode.Debug.Tests")]
[assembly: AssemblyProduct("BitCode")]
[assembly: AssemblyCompany("24 Bit Games")]
[assembly: InternalsVisibleTo("BitCode.Editor.AssetManagement")]
[assembly: InternalsVisibleTo("BitCode.AssetManagement")]
[assembly: AlwaysLinkAssembly]
[assembly: InternalsVisibleTo("BitCode.Editor")]
[assembly: InternalsVisibleTo("BitCode.Platform.XboxOne")]
[assembly: InternalsVisibleTo("BitCode.Platform.NX")]
[assembly: InternalsVisibleTo("BitCode.Platform.EpicOnlineServices")]
[assembly: InternalsVisibleTo("BitCode.Platform.WindowsGamePass")]
[assembly: InternalsVisibleTo("BitCode.Platform.PS5")]
[assembly: InternalsVisibleTo("BitCode.Editor.Build.GameCore")]
[assembly: InternalsVisibleTo("BitCode.Editor.Build")]
[assembly: InternalsVisibleTo("BitCode.Platform.PS4")]
[assembly: InternalsVisibleTo("BitCode.Platform")]
[assembly: AssemblyVersion("27.0.0.0")]
[module: ConfusedBy("ConfuserEx v1.0.0-31-g1affd8b")]
