public enum CheatReason
{
	NONE = 0,
	UNLIMITED_MATERIAL = 1,
	UNLIMITED_BUDGET = 2,
	COST_EXCEEDS_HARD_BUDGET = 3,
	INVALID_EDGE_LENGTH = 4,
	ILLEGAL_NODE_PLACEMENT = 5,
	SPLIT_JOINTS_WITHOUT_HYDRAULICS_PHASE = 6,
	USING_GAMEPLAY_MOD = 7,
	MATERIAL_NOT_ALLOWED = 8,
	MATERIAL_BEYOND_BUDGET = 9,
	PREBUILT_MATERIALS_MODIFIED = 10,
	INVALID_BRIDGE_PILLAR_HEIGHT = 11,
	BUILT_OUTSIDE_BUILD_ZONES = 12,
	ILLEGAL_SPRING_ADJUSTMENTS = 13,
	ILLEGAL_FOUNDATION_PLACEMENT = 14,
	VEHICLE_JOINT_BROKEN = 64,
	VEHICLE_HIGH_ACCELERATION = 65
}
