using System;
using System.Collections.Generic;
using Poly;
using Poly.Collide;
using Poly.Collide.Unity;
using Poly.Math;
using Poly.Physics;
using UnityEngine;

public class CustomShape : MonoBehaviour
{
	public static readonly int MAX_VERTS = 100;

	[Header("Mesh")]
	public GameObject m_AutoGeneratedMesh;

	public MeshFilter m_MeshFilter;

	public MeshRenderer m_MeshRenderer;

	public CustomShapeCollisionInfo m_CollisionInfo;

	[Header("Containers")]
	public GameObject m_VertsParent;

	public GameObject m_PinsParent;

	public GameObject m_AnchorsParent;

	[Header("Physics")]
	public PolygonCollider2D m_PolygonCollider2D;

	public bool m_CollidesWithVehicles;

	public bool m_CollidesWithRoad;

	public bool m_CollidesWithNodes;

	public bool m_CollidesWithRamps;

	public bool m_CollidesWithSplitNodes;

	[NonSerialized]
	public Color m_Color;

	[NonSerialized]
	public float m_RotationDegrees;

	[NonSerialized]
	public float m_Mass;

	[NonSerialized]
	public float m_Thickness;

	[NonSerialized]
	public float m_Bounciness;

	[NonSerialized]
	public float m_PinMotorStrength;

	[NonSerialized]
	public float m_PinTargetVelocity;

	[NonSerialized]
	public float m_PinTargetAccelerationSeconds;

	[NonSerialized]
	public bool m_Flipped;

	[NonSerialized]
	public bool m_LowFriction;

	[NonSerialized]
	public Poly.Physics.Rigidbody m_PhysicsBodyIfDynamic;

	[NonSerialized]
	public SandboxItem m_SandboxItem;

	[NonSerialized]
	public Vector3 m_GridOffset;

	[NonSerialized]
	public CustomShapeBehavior m_Behavior;

	[NonSerialized]
	public float m_DisableMeshRenderingTime;

	[NonSerialized]
	public string m_MeshId;

	[NonSerialized]
	public GameObject m_CustomMesh;

	[NonSerialized]
	public Vector3 m_CustomMeshScale;

	[NonSerialized]
	public CustomShapeTexture m_Texture;

	[NonSerialized]
	public float m_TextureTiling;

	[NonSerialized]
	public Vector3 m_SpawnPos;

	[NonSerialized]
	public Quaternion m_SpawnRot;

	[NonSerialized]
	public List<CustomShapeVert> m_Verts = new List<CustomShapeVert>();

	[NonSerialized]
	public List<CustomShapeEdge> m_Edges = new List<CustomShapeEdge>();

	[NonSerialized]
	public bool m_Dirty;

	[NonSerialized]
	public List<CustomShapePin> m_Pins = new List<CustomShapePin>();

	[NonSerialized]
	public List<CustomShapeAnchor> m_Anchors = new List<CustomShapeAnchor>();

	[NonSerialized]
	public string m_FullyQualifiedPath;

	private Outline m_Outline;

	private bool m_HasCreatedOutline;

	private bool m_PlayedSplashFX;

	private bool m_WasUnderWaterAtSimulationStart;

	internal List<PolygonShape> m_PolygonShapes = new List<PolygonShape>();

	private MaterialPropertyBlock m_MaterialPropertyBlock;

	private Vector3 m_StubBeingPreloadedLocalPosition;

	private float m_StubBeingPreloadedEnableMeshForSeconds;

	private bool m_HighlightedInBuildMode;

	private const string INVISIBLE_TEXTURE_LOC_ID = "TEXTURE_INVISIBLE";

	private Vec2 centerOfMassPosition
	{
		get
		{
			if (!m_PhysicsBodyIfDynamic || !m_PhysicsBodyIfDynamic.isAddedToWorld)
			{
				return (Vec2)base.transform.position;
			}
			return m_PhysicsBodyIfDynamic.t2 * -m_PhysicsBodyIfDynamic.engine_comTbody;
		}
	}

	private void Awake()
	{
		m_SandboxItem = GetComponent<SandboxItem>();
		m_Mass = CustomShapes.DEFAULT_MASS;
		m_Bounciness = CustomShapes.DEFAULT_BOUNCINESS;
		m_PinMotorStrength = CustomShapes.DEFAULT_PIN_MOTOR_STRENGTH;
		m_PinTargetVelocity = CustomShapes.DEFAULT_PIN_TARGET_VELOCITY;
		m_PinTargetAccelerationSeconds = CustomShapes.DEFAULT_PIN_TARGET_ACCELERATION_SECONDS;
		m_MaterialPropertyBlock = new MaterialPropertyBlock();
		m_DisableMeshRenderingTime = float.MaxValue;
		m_CustomMeshScale = Vector3.one;
		m_CollisionInfo = GetComponentInChildren<CustomShapeCollisionInfo>();
	}

	private void OnDestroy()
	{
		if (CustomShapes.m_Shapes.Contains(this))
		{
			CustomShapes.m_Shapes.Remove(this);
		}
		DestroyVertsAndEdges();
	}

	public void UpdateManual()
	{
		if (Bridge.IsSimulating() && (bool)m_PhysicsBodyIfDynamic)
		{
			Transform3 interpolatedTransform = m_PhysicsBodyIfDynamic.interpolatedTransform;
			base.transform.position = interpolatedTransform.position;
			base.transform.rotation = interpolatedTransform.rotation;
			MaybePlaySplashFX();
		}
	}

	public void LateUpdateManual()
	{
		if (GameStateManager.GetState() == GameState.BUILD)
		{
			if (GameStateBuild.CustomShapeHasHoverFocus(this) && !m_HighlightedInBuildMode)
			{
				m_Outline.SetColor(GameUI.m_Instance.m_GoldColor);
				m_Outline.m_VectorLine.texture = GameUI.m_Instance.m_ChalkLine2D;
				m_Outline.SetWidth(GameUI.m_Instance.GetOutlineWidth(GameState.BUILD) * 2f);
				m_HighlightedInBuildMode = true;
			}
			if (m_HighlightedInBuildMode && !GameStateBuild.CustomShapeHasHoverFocus(this))
			{
				m_Outline.SetColor(Color.white);
				m_Outline.m_VectorLine.texture = GetOutlineTextureForBuildMode();
				m_Outline.SetWidth(GameUI.m_Instance.GetOutlineWidth(GameState.BUILD) * m_Outline.m_BuildModeWidthMultiplier);
				m_HighlightedInBuildMode = false;
			}
		}
	}

	public void FixedUpdateManual()
	{
	}

	public void MaybeDisableMeshRendering()
	{
		if (Time.realtimeSinceStartup > m_DisableMeshRenderingTime && (!GameUI.m_Instance.m_SandboxEditCustomShape.gameObject.activeInHierarchy || !(SandboxSelectionSet.GetSelectedItem() == m_SandboxItem)))
		{
			EnableMeshRendering(on: false);
			m_DisableMeshRenderingTime = float.MaxValue;
		}
	}

	public bool CollidesWithSplitNodes()
	{
		if (!m_CollidesWithRoad)
		{
			return m_CollidesWithNodes;
		}
		return true;
	}

	public void Restore()
	{
		base.transform.position = m_SpawnPos;
		base.transform.rotation = m_SpawnRot;
		m_PlayedSplashFX = false;
		m_WasUnderWaterAtSimulationStart = false;
	}

	public void OnAddToSimulation()
	{
		m_WasUnderWaterAtSimulationStart = CenterPointUnderWater();
	}

	public void EndSimulation()
	{
		if ((bool)m_PhysicsBodyIfDynamic)
		{
			UnityEngine.Object.Destroy(m_PhysicsBodyIfDynamic.gameObject);
			m_PhysicsBodyIfDynamic = null;
		}
	}

	public void DisableOutline()
	{
		m_SandboxItem.m_OutlineGroup.DisableOutline();
	}

	public void EnableMeshRendering(bool on)
	{
		m_MeshRenderer.gameObject.SetActive(on);
		ShowPinMeshes(on);
		MovePinsToFrontOfMesh();
	}

	public bool UsingInvisibleMaterial()
	{
		if ((bool)m_Texture)
		{
			return m_Texture.m_DisplayNameLocID == "TEXTURE_INVISIBLE";
		}
		return false;
	}

	public bool IsDynamicProp()
	{
		if (m_CustomMesh != null)
		{
			return m_CustomMesh.gameObject.activeInHierarchy;
		}
		return false;
	}

	public void HideInvisibleMaterial()
	{
		if (UsingInvisibleMaterial())
		{
			EnableMeshRendering(on: false);
		}
	}

	public void UpdateOutline()
	{
		if (!m_HasCreatedOutline)
		{
			m_Outline = m_SandboxItem.m_OutlineGroup.CreateOutline(GameUI.m_Instance.m_OutlineTextureSandbox, GameUI.m_Instance.m_OutlineTextureScale, GameUI.m_Instance.m_OutlineWidthSandbox);
			m_Outline.SetTextureScale(GameUI.m_Instance.m_OutlineTextureScale);
			m_HasCreatedOutline = true;
			m_SandboxItem.SetOutlineDirty(dirty: true);
		}
		if (m_SandboxItem.IsOutlineDirty())
		{
			m_SandboxItem.UpdateOutlineFromPolygonCollider2D(m_Outline, m_PolygonCollider2D);
			m_SandboxItem.SetOutlineDirty(dirty: false);
			m_Outline.m_VectorLine.Draw3DAuto();
		}
	}

	public void EnterSandboxMode()
	{
		EnableMeshRendering(on: false);
	}

	public void EnterBuildMode()
	{
		if (m_Outline == null)
		{
			UpdateOutline();
		}
		if (m_Outline != null)
		{
			m_Outline.SetTexture(GetOutlineTextureForBuildMode());
		}
		EnableMeshRendering(!UsingInvisibleMaterial());
	}

	public void EnterSimMode()
	{
		EnableMeshRendering(!UsingInvisibleMaterial());
	}

	public void UpdatePolygonShapes()
	{
		bool calculateMinimumStrengthHint = m_Behavior == CustomShapeBehavior.MOTORIZED;
		m_PolygonShapes.Clear();
		m_PolygonShapes.AddRange(m_CollisionInfo.CreatePolygonShapes_ForBuildMode(calculateMinimumStrengthHint));
		m_SandboxItem.SetOutlineDirty(dirty: true);
	}

	public bool OverlapsPolygonShape(PolygonShape shape)
	{
		return Utils.PolygonShapeOverlapsShapes(shape, m_PolygonShapes);
	}

	public void RecalculatePivot()
	{
		Vector3 position = base.gameObject.transform.position;
		Vector3 zero = Vector3.zero;
		if (m_Pins.Count == 1)
		{
			zero = new Vector3(m_Pins[0].transform.position.x, m_Pins[0].transform.position.y, position.z);
		}
		else
		{
			Quaternion rotation = base.gameObject.transform.rotation;
			base.gameObject.transform.rotation = Quaternion.identity;
			Bounds bounds = new Bounds(m_Verts[0].transform.position, Vector3.zero);
			foreach (CustomShapeVert vert in m_Verts)
			{
				bounds.Encapsulate(vert.transform.position);
			}
			base.gameObject.transform.rotation = rotation;
			Vector3 vector = new Vector3(bounds.center.x, bounds.center.y, position.z);
			zero = rotation * (vector - position) + position;
			if (Mathf.Approximately((base.transform.position - zero).magnitude, 0f))
			{
				return;
			}
		}
		foreach (CustomShapeVert vert2 in m_Verts)
		{
			vert2.transform.localPosition = base.gameObject.transform.InverseTransformVector(vert2.transform.position - zero);
		}
		foreach (CustomShapePin pin in m_Pins)
		{
			pin.transform.localPosition = base.gameObject.transform.InverseTransformVector(pin.transform.position - zero);
		}
		foreach (CustomShapeAnchor anchor in m_Anchors)
		{
			anchor.transform.localPosition = base.gameObject.transform.InverseTransformVector(anchor.transform.position - zero);
		}
		base.gameObject.transform.position = new Vector3(zero.x, zero.y, (m_Anchors.Count > 0) ? 0f : position.z);
		RecalculateGridOffset();
		UpdateSpawnTransform();
		MarkAllAnchorOutlinesDirty();
		if (m_MeshId != CustomShapes.AUTO_GENERATED_MESH_ID)
		{
			Vector3 vector2 = base.gameObject.transform.position - position;
			m_MeshRenderer.transform.position -= vector2;
		}
		m_Dirty = true;
	}

	public void RecalculateGridOffset()
	{
		m_GridOffset = base.transform.position - GameGrid.SnapPosToGridForced(base.transform.position);
	}

	public void RebuildCollider()
	{
		Vector2[] array = new Vector2[m_Verts.Count];
		for (int i = 0; i < m_Verts.Count; i++)
		{
			array[i] = m_PolygonCollider2D.transform.InverseTransformPoint(m_Verts[i].transform.position);
		}
		m_PolygonCollider2D.SetPath(0, array);
		UpdatePolygonShapes();
	}

	public Vector2[] GetVerticesInWorldSpace()
	{
		Vector2[] array = new Vector2[m_Verts.Count];
		for (int i = 0; i < m_Verts.Count; i++)
		{
			array[i] = m_Verts[i].transform.position;
		}
		return array;
	}

	public void RebuildMesh()
	{
		MakeMeshFromPolygonCollider();
		ExtrudeMesh(m_Thickness);
		MovePinsToFrontOfMesh();
	}

	public void UseCustomMesh(string customMeshId, Vector3 localPosition, float enableMeshForSeconds)
	{
		m_StubBeingPreloadedLocalPosition = localPosition;
		m_StubBeingPreloadedEnableMeshForSeconds = enableMeshForSeconds;
		if (Prefabs.AsyncPrefabExists(customMeshId))
		{
			ObjectPreloadedCallback(customMeshId, string.Empty, success: true);
		}
		else
		{
			Prefabs.m_Instance.PreloadSingleAsset(customMeshId, string.Empty, ObjectPreloadedCallback);
		}
	}

	private void ObjectPreloadedCallback(string addressableName, string instanceID, bool success)
	{
		GameObject asyncPrefab = Prefabs.GetAsyncPrefab(addressableName);
		if (asyncPrefab == null)
		{
			Debug.LogWarningFormat("Could not find preloaded prefab with address " + addressableName);
			return;
		}
		if (m_CustomMesh != null)
		{
			UnityEngine.Object.Destroy(m_CustomMesh);
		}
		m_CustomMesh = UnityEngine.Object.Instantiate(asyncPrefab, base.transform);
		if (!(m_CustomMesh == null))
		{
			m_MeshRenderer.gameObject.SetActive(value: false);
			m_MeshRenderer = m_CustomMesh.GetComponentInChildren<MeshRenderer>();
			m_MeshRenderer.transform.localPosition = m_StubBeingPreloadedLocalPosition;
			m_CustomMesh.transform.localScale = m_CustomMeshScale;
			if (m_StubBeingPreloadedEnableMeshForSeconds > 0f)
			{
				m_DisableMeshRenderingTime = Time.realtimeSinceStartup + m_StubBeingPreloadedEnableMeshForSeconds;
			}
			else
			{
				m_MeshRenderer.gameObject.SetActive(GameStateManager.GetState() != GameState.SANDBOX);
			}
		}
	}

	public void UpdateShaderProperties(Color color, bool buildMode)
	{
		m_Color = color;
		m_MaterialPropertyBlock.SetFloat(ShaderVariables_SimpleLitCollidable.BUILD_MODE_SHADER_ID, buildMode ? 1f : 0f);
		m_MaterialPropertyBlock.SetColor(ShaderVariables_SimpleLitCollidable.BUILD_MODE_TINT_SHADER_ID, (m_CollidesWithNodes || m_CollidesWithRoad) ? PostFX.m_Instance.m_BuildModeCollideTint : PostFX.m_Instance.m_BuildModeCustomShapeNoCollide);
		m_MaterialPropertyBlock.SetColor(ShaderVariables_Common.ALBEDO_COLOR_SHADER_ID, color);
		m_MaterialPropertyBlock.SetVector(ShaderVariables_Common.TILING_SHADER_ID, new Vector2(m_TextureTiling, m_TextureTiling));
		if (m_Texture != null && m_Texture.m_Texture != null)
		{
			m_MaterialPropertyBlock.SetTexture(ShaderVariables_SimpleLitCollidable.ALBEDO_SHADER_ID, m_Texture.m_Texture);
		}
		m_MeshRenderer.SetPropertyBlock(m_MaterialPropertyBlock);
	}

	public void ShowVerts()
	{
		m_VertsParent.SetActive(value: true);
	}

	public void HideVerts()
	{
		m_VertsParent.SetActive(value: false);
	}

	public void ShowPins()
	{
		m_PinsParent.SetActive(value: true);
	}

	public void HidePins()
	{
		m_PinsParent.SetActive(value: false);
	}

	public void ShowAnchors()
	{
		m_AnchorsParent.SetActive(value: true);
	}

	public void HideAnchors()
	{
		m_AnchorsParent.SetActive(value: false);
	}

	public void DestroyVert(CustomShapeVert vert)
	{
		if (!m_Verts.Contains(vert))
		{
			return;
		}
		m_Verts.Remove(vert);
		UnityEngine.Object.Destroy(vert.gameObject);
		CustomShapeEdge customShapeEdge = null;
		for (int i = 0; i < m_Edges.Count; i++)
		{
			if (m_Edges[i].m_VertA == vert)
			{
				customShapeEdge = m_Edges[i];
			}
		}
		for (int j = 0; j < m_Edges.Count; j++)
		{
			if (m_Edges[j].m_VertB == vert)
			{
				m_Edges[j].m_VertB = customShapeEdge.m_VertB;
			}
		}
		m_Edges.Remove(customShapeEdge);
	}

	public void DestroyPin(CustomShapePin pin)
	{
		if (m_Pins.Contains(pin))
		{
			m_Pins.Remove(pin);
		}
		UnityEngine.Object.Destroy(pin.gameObject);
	}

	public void DestroyAnchor(CustomShapeAnchor anchor)
	{
		BridgeJoint bridgeJoint = BridgeJoints.FindByGuid(anchor.m_BridgeJointGuid);
		if ((bool)bridgeJoint)
		{
			BridgeJoints.DestroyAnchors(new List<BridgeJoint> { bridgeJoint });
		}
		if (m_Anchors.Contains(anchor))
		{
			m_Anchors.Remove(anchor);
		}
		anchor.gameObject.SetActive(value: false);
		UnityEngine.Object.Destroy(anchor.gameObject);
	}

	public Vector3 GetNearestPosOnOutline(Vector3 worldPos)
	{
		Vector3 vector = new Vector3(float.MaxValue, float.MaxValue, 0f);
		foreach (CustomShapeEdge edge in m_Edges)
		{
			Vector3 start = new Vector3(edge.m_VertA.transform.position.x, edge.m_VertA.transform.position.y, 0f);
			Vector3 end = new Vector3(edge.m_VertB.transform.position.x, edge.m_VertB.transform.position.y, 0f);
			Vector3 vector2 = Utils.NearestPointOnLineSegment(start, end, worldPos);
			if (Vector2.Distance(vector2, worldPos) < Vector2.Distance(vector, worldPos))
			{
				vector = vector2;
			}
		}
		return vector;
	}

	public CustomShapeEdge GetNearestEdge(Vector3 worldPos)
	{
		Vector3 a = new Vector3(float.MaxValue, float.MaxValue, 0f);
		CustomShapeEdge result = null;
		foreach (CustomShapeEdge edge in m_Edges)
		{
			Vector3 vector = Utils.NearestPointOnLineSegment(edge.m_VertA.transform.position, edge.m_VertB.transform.position, worldPos);
			if (Vector3.Distance(vector, worldPos) < Vector3.Distance(a, worldPos))
			{
				a = vector;
				result = edge;
			}
		}
		return result;
	}

	public CustomShapeVert InsertVertOnEdge(CustomShapeEdge edge, Vector2 worldPos)
	{
		int num = m_Edges.IndexOf(edge);
		if (num < 0)
		{
			Debug.LogWarning("Coult not find edge on insertion");
			return null;
		}
		_ = edge.m_VertA;
		CustomShapeVert vertB = edge.m_VertB;
		int num2 = m_Verts.IndexOf(edge.m_VertA);
		CustomShapeVert customShapeVert = CreateVert(Vector3.zero);
		if ((bool)customShapeVert)
		{
			customShapeVert.transform.position = new Vector3(worldPos.x, worldPos.y, base.transform.position.z);
			m_Verts.Insert(num2 + 1, customShapeVert);
			edge.m_VertB = customShapeVert;
			CustomShapeEdge customShapeEdge = new CustomShapeEdge();
			customShapeEdge.m_VertA = customShapeVert;
			customShapeEdge.m_VertB = vertB;
			m_Edges.Insert(num + 1, customShapeEdge);
			customShapeVert.InverseScale(base.transform.localScale);
		}
		return customShapeVert;
	}

	public void InitializeFromParameters(int edgeCount, float radius, Color color)
	{
		m_Color = color;
		m_PolygonCollider2D.CreatePrimitive(edgeCount, new Vector2(radius, radius));
		Initialize();
	}

	public void InitializeFromPointsList(List<Vector2> pointsLocalSpace)
	{
		Vector2[] pointsLocalSpace2 = pointsLocalSpace.ToArray();
		InitializeFromPointsArray(pointsLocalSpace2);
	}

	public void InitializeFromPointsArray(Vector2[] pointsLocalSpace)
	{
		m_PolygonCollider2D.SetPath(0, pointsLocalSpace);
		Initialize();
	}

	public void CreateVertsAndEdges()
	{
		m_Verts.Clear();
		m_Edges.Clear();
		for (int i = 0; i < m_PolygonCollider2D.points.Length; i++)
		{
			CustomShapeVert customShapeVert = CreateVert(m_PolygonCollider2D.points[i]);
			if (customShapeVert != null)
			{
				m_Verts.Add(customShapeVert);
				if (i > 0)
				{
					CustomShapeEdge customShapeEdge = new CustomShapeEdge();
					customShapeEdge.m_VertA = m_Verts[i - 1];
					customShapeEdge.m_VertB = m_Verts[i];
					m_Edges.Add(customShapeEdge);
				}
			}
		}
		CustomShapeEdge customShapeEdge2 = new CustomShapeEdge();
		customShapeEdge2.m_VertA = m_Verts[m_Verts.Count - 1];
		customShapeEdge2.m_VertB = m_Verts[0];
		m_Edges.Add(customShapeEdge2);
	}

	public void DestroyVertsAndEdges()
	{
		foreach (CustomShapeVert vert in m_Verts)
		{
			vert.gameObject.SetActive(value: false);
			UnityEngine.Object.Destroy(vert.gameObject);
		}
		m_Verts.Clear();
		m_Edges.Clear();
	}

	public void DestroyPins()
	{
		foreach (CustomShapePin pin in m_Pins)
		{
			pin.gameObject.SetActive(value: false);
			UnityEngine.Object.Destroy(pin.gameObject);
		}
		m_Pins.Clear();
	}

	public void DestroyAnchors()
	{
		foreach (CustomShapeAnchor anchor in m_Anchors)
		{
			anchor.gameObject.SetActive(value: false);
			UnityEngine.Object.Destroy(anchor.gameObject);
		}
		m_Anchors.Clear();
	}

	public bool OverlapsPoint(Vector3 pos)
	{
		return m_PolygonCollider2D.OverlapPoint(pos);
	}

	public bool ContainsAnchorGuid(string guid)
	{
		foreach (CustomShapeAnchor anchor in m_Anchors)
		{
			if (anchor.m_BridgeJointGuid == guid)
			{
				return true;
			}
		}
		return false;
	}

	public void SetLocalScale(Vector3 localScale)
	{
		base.transform.localScale = localScale;
		DestroyVertsAndEdges();
		CreateVertsAndEdges();
		UpdateVisualScale();
	}

	public bool IsStatic()
	{
		return m_Behavior == CustomShapeBehavior.STATIC;
	}

	public bool IsDynamic()
	{
		return !IsStatic();
	}

	public bool IsMotorized()
	{
		return m_Behavior == CustomShapeBehavior.MOTORIZED;
	}

	public void MovePinsToFrontOfMesh()
	{
		foreach (CustomShapePin pin in m_Pins)
		{
			pin.transform.localPosition = new Vector3(pin.transform.localPosition.x, pin.transform.localPosition.y, m_MeshRenderer.transform.localPosition.z);
		}
	}

	public bool AddAnchor(Vector3 worldPos)
	{
		CustomShapeAnchor customShapeAnchor = CustomShapes.CreateAnchor(worldPos, m_AnchorsParent.transform, base.transform.localScale);
		if ((bool)customShapeAnchor)
		{
			m_Anchors.Add(customShapeAnchor);
			BridgeJoint bridgeJoint = CreateStaticJoint(customShapeAnchor.transform.position, customShapeAnchor.transform);
			customShapeAnchor.m_BridgeJointGuid = (bridgeJoint ? bridgeJoint.m_Guid : string.Empty);
			customShapeAnchor.m_SpriteRenderer.gameObject.SetActive(value: false);
			bridgeJoint.m_SandboxItem.SetOutlineDirty(dirty: true);
			return true;
		}
		return false;
	}

	public CustomShapePin AddPin(Vector3 worldPos)
	{
		CustomShapePin customShapePin = CustomShapes.CreatePin(worldPos, m_PinsParent.transform, base.transform.localScale);
		if ((bool)customShapePin)
		{
			m_Pins.Add(customShapePin);
			return customShapePin;
		}
		return null;
	}

	public void RemovePinsOutsideShape()
	{
		for (int num = m_Pins.Count - 1; num >= 0; num--)
		{
			CustomShapePin customShapePin = m_Pins[num];
			if (!OverlapsPoint(customShapePin.transform.position))
			{
				DestroyPin(customShapePin);
			}
		}
	}

	public void RemoveAnchorsOutsideShape()
	{
		for (int num = m_Anchors.Count - 1; num >= 0; num--)
		{
			CustomShapeAnchor customShapeAnchor = m_Anchors[num];
			if (!OverlapsPoint(customShapeAnchor.transform.position))
			{
				DestroyAnchor(customShapeAnchor);
			}
		}
	}

	public void Flip(bool flipped)
	{
		base.transform.localScale = new Vector3(flipped ? (0f - Mathf.Abs(base.transform.localScale.x)) : Mathf.Abs(base.transform.localScale.x), base.transform.localScale.y, base.transform.localScale.z);
		UpdateVisualScale();
		m_SandboxItem.SetOutlineDirty(dirty: true);
		MarkAllAnchorOutlinesDirty();
	}

	public void UpdateSpawnTransform()
	{
		m_SpawnPos = base.transform.position;
		m_SpawnRot = base.transform.rotation;
	}

	public CustomShape Duplicate(GameObject prefab, Vector3 offset)
	{
		CustomShape customShape = CustomShapes.CreateCustomShape(prefab, base.transform.position, base.transform.rotation);
		if (!customShape)
		{
			return null;
		}
		customShape.m_RotationDegrees = m_RotationDegrees;
		customShape.m_Mass = m_Mass;
		customShape.m_Bounciness = m_Bounciness;
		customShape.m_PinMotorStrength = m_PinMotorStrength;
		customShape.m_PinTargetVelocity = m_PinTargetVelocity;
		customShape.m_PinTargetAccelerationSeconds = m_PinTargetAccelerationSeconds;
		customShape.m_Color = m_Color;
		customShape.m_CollidesWithVehicles = m_CollidesWithVehicles;
		customShape.m_CollidesWithNodes = m_CollidesWithNodes;
		customShape.m_CollidesWithRamps = m_CollidesWithRamps;
		customShape.m_CollidesWithRoad = m_CollidesWithRoad;
		customShape.m_CollidesWithSplitNodes = m_CollidesWithSplitNodes;
		customShape.m_Behavior = m_Behavior;
		customShape.m_Thickness = m_Thickness;
		customShape.m_LowFriction = m_LowFriction;
		customShape.m_Texture = CustomShapeTextures.m_Instance.GetTextureFromId(m_Texture.m_ID);
		customShape.m_TextureTiling = m_TextureTiling;
		customShape.m_MeshId = m_MeshId;
		if (customShape.m_MeshId != CustomShapes.AUTO_GENERATED_MESH_ID)
		{
			customShape.UseCustomMesh(customShape.m_MeshId, m_MeshRenderer.transform.localPosition, 0f);
			customShape.m_CustomMeshScale = m_CustomMeshScale;
			customShape.m_CustomMesh.transform.localScale = m_CustomMeshScale;
			customShape.m_AutoGeneratedMesh.SetActive(value: false);
		}
		customShape.InitializeFromPointsArray(m_PolygonCollider2D.points);
		customShape.SetLocalScale(base.transform.localScale);
		DuplicateDynamicAnchors(customShape);
		DuplicatePins(customShape);
		customShape.transform.position += offset;
		customShape.UpdatePolygonShapes();
		customShape.EnableMeshRendering(on: false);
		return customShape;
	}

	public void UpdateAfterRotation()
	{
		foreach (CustomShapeAnchor anchor in m_Anchors)
		{
			anchor.transform.rotation = Quaternion.identity;
			MarkAllAnchorOutlinesDirty();
		}
	}

	public void ShowStaticPins()
	{
		foreach (CustomShapePin pin in m_Pins)
		{
			pin.gameObject.SetActive(value: true);
		}
	}

	public void HideStaticPins()
	{
		foreach (CustomShapePin pin in m_Pins)
		{
			pin.gameObject.SetActive(value: false);
		}
	}

	public void ShowAnchorMeshes(bool show)
	{
		foreach (CustomShapeAnchor anchor in m_Anchors)
		{
			BridgeJoint bridgeJoint = BridgeJoints.FindByGuid(anchor.m_BridgeJointGuid);
			if ((bool)bridgeJoint)
			{
				bridgeJoint.m_Cap.SetActive(show);
			}
			anchor.m_SpriteRenderer.gameObject.SetActive(value: false);
		}
	}

	public void MarkAllAnchorOutlinesDirty()
	{
		foreach (CustomShapeAnchor anchor in m_Anchors)
		{
			BridgeJoint bridgeJoint = BridgeJoints.FindByGuid(anchor.m_BridgeJointGuid);
			if ((bool)bridgeJoint)
			{
				bridgeJoint.m_SandboxItem.SetOutlineDirty(dirty: true);
			}
		}
	}

	public void ShowPinMeshes(bool show)
	{
		foreach (CustomShapePin pin in m_Pins)
		{
			pin.ShowMesh(show);
			if (UsingInvisibleMaterial())
			{
				pin.ShowSprite(GameStateManager.GetState() != GameState.SIM);
			}
		}
	}

	public void UpdateVisualScale()
	{
		foreach (CustomShapeVert vert in m_Verts)
		{
			vert.InverseScale(base.transform.localScale);
		}
		foreach (CustomShapeAnchor anchor in m_Anchors)
		{
			anchor.InverseScale(base.transform.localScale);
		}
		foreach (CustomShapePin pin in m_Pins)
		{
			pin.InverseScale(base.transform.localScale);
		}
	}

	public float GetDesiredAcceleration()
	{
		if (Mathf.Approximately(m_PinTargetAccelerationSeconds, 0f))
		{
			return float.MaxValue;
		}
		return Mathf.Abs(m_PinTargetVelocity / m_PinTargetAccelerationSeconds);
	}

	private void DuplicateDynamicAnchors(CustomShape dest)
	{
		foreach (CustomShapeAnchor anchor in m_Anchors)
		{
			dest.AddAnchor(anchor.transform.position);
		}
	}

	private void DuplicatePins(CustomShape dest)
	{
		foreach (CustomShapePin pin in m_Pins)
		{
			CustomShapePin customShapePin = dest.AddPin(pin.transform.position);
			if (customShapePin != null)
			{
				customShapePin.ShowMesh(show: false);
			}
		}
	}

	private void Initialize()
	{
		CreateVertsAndEdges();
		HideVerts();
		if (m_MeshId == CustomShapes.AUTO_GENERATED_MESH_ID)
		{
			RebuildMesh();
			UpdateShaderProperties(m_Color, buildMode: false);
		}
	}

	private CustomShapeVert CreateVert(Vector2 localPos)
	{
		Vector2 vector = m_PolygonCollider2D.transform.TransformPoint(localPos);
		GameObject gameObject = UnityEngine.Object.Instantiate(Prefabs.m_Instance.m_CustomShapeVert, new Vector3(vector.x, vector.y, base.transform.position.z), Quaternion.identity, m_VertsParent.transform);
		if (!gameObject)
		{
			return null;
		}
		return gameObject.GetComponent<CustomShapeVert>();
	}

	private bool MakeMeshFromPolygonCollider()
	{
		int[] triangles = new TriangulatorBridges(m_PolygonCollider2D.points).Triangulate();
		Vector3[] array = new Vector3[m_PolygonCollider2D.points.Length];
		Vector2[] array2 = new Vector2[m_PolygonCollider2D.points.Length];
		for (int i = 0; i < array.Length; i++)
		{
			array[i] = new Vector3(m_PolygonCollider2D.points[i].x, m_PolygonCollider2D.points[i].y, 0f);
		}
		Vector3 vector = new Vector3(float.MaxValue, float.MaxValue, 0f);
		Vector3 vector2 = new Vector3(float.MinValue, float.MinValue, 0f);
		Vector3[] array3 = array;
		for (int j = 0; j < array3.Length; j++)
		{
			Vector3 vector3 = array3[j];
			if (vector3.x < vector.x)
			{
				vector.x = vector3.x;
			}
			if (vector3.y < vector.y)
			{
				vector.y = vector3.y;
			}
			if (vector3.x > vector2.x)
			{
				vector2.x = vector3.x;
			}
			if (vector3.y > vector2.y)
			{
				vector2.y = vector3.y;
			}
		}
		for (int k = 0; k < array.Length; k++)
		{
			Vector3 vector4 = array[k];
			array2[k].x = 0.1f * Mathf.Abs(vector4.x - vector.x);
			array2[k].y = 0.1f * Mathf.Abs(vector4.y - vector.y);
		}
		Mesh mesh = new Mesh();
		mesh.vertices = array;
		mesh.uv = array2;
		mesh.triangles = triangles;
		mesh.RecalculateNormals();
		mesh.RecalculateBounds();
		mesh.RecalculateNormals();
		bool flag = false;
		for (int l = 0; l < mesh.normals.Length; l++)
		{
			if (mesh.normals[l].z > 0f)
			{
				flag = true;
			}
		}
		if (flag)
		{
			return false;
		}
		m_MeshFilter.mesh = mesh;
		return true;
	}

	private void ExtrudeMesh(float distance)
	{
		Mesh mesh = new Mesh();
		MeshExtrusion.ExtrudeMesh(m_MeshFilter.mesh, mesh, distance);
		m_MeshRenderer.transform.localPosition = new Vector3(m_MeshRenderer.transform.localPosition.x, m_MeshRenderer.transform.localPosition.y, (0f - distance) / 2f);
		m_MeshFilter.mesh = mesh;
	}

	private Texture GetOutlineTextureForBuildMode()
	{
		if (m_CollidesWithNodes || m_CollidesWithRoad || m_CollidesWithRamps)
		{
			return GameUI.m_Instance.m_OutlineTextureBuildMode;
		}
		return GameUI.m_Instance.m_OutlineTextureDashedBuildMode;
	}

	private BridgeJoint CreateStaticJoint(Vector3 pos, Transform parent)
	{
		BridgeJoint bridgeJoint = BridgeJoints.CreateAnchor(pos, Utils.GenerateUniqueId());
		if (!bridgeJoint)
		{
			return null;
		}
		bridgeJoint.m_SandboxItem = SandboxItems.AddSandboxItemComponent(bridgeJoint.gameObject, SandboxItemType.ANCHOR);
		bridgeJoint.transform.parent = parent;
		return bridgeJoint;
	}

	private void MaybePlaySplashFX()
	{
		if (!m_PlayedSplashFX && !m_WasUnderWaterAtSimulationStart)
		{
			WaterBlock waterBlock = CenterPointUnderWater();
			if ((bool)waterBlock)
			{
				PlaySplashFX(waterBlock);
			}
		}
	}

	private void PlaySplashFX(WaterBlock waterBlock)
	{
		WaterSplash.Play(new Vector3(centerOfMassPosition.x, waterBlock.m_Height + 0.1f, base.transform.position.z), WaterSplashSize.BIG, waterBlock);
		m_PlayedSplashFX = true;
	}

	public WaterBlock CenterPointUnderWater()
	{
		if (m_PhysicsBodyIfDynamic == null || SandboxSettings.m_NoWater)
		{
			return null;
		}
		return WaterBlocks.PositionInWater(base.transform.position);
	}
}
