public enum PlacementReturnValue
{
	SUCCESS = 0,
	FAIL = 1,
	FAIL_NO_MATERIAL_LEFT = 2,
	FAIL_CANNOT_AFFORD_COST = 3,
	FAIL_OUTSIDE_WORLD_BOUNDS = 4,
	FAIL_NODE_ILLEGAL_POSITION = 5,
	FAIL_EDGE_OVERLAPS_BLOCKING_SHAPE = 6,
	FAIL_OUTSIDE_BUILD_ZONE = 7,
	FAIL_NO_BUILD_ANCHOR = 8,
	FAIL_EXCEEDS_MAX_EDGE_LIMIT_PER_NODE = 9,
	FAIL_PILLAR_OVERLAPS_BLOCKING_SHAPE = 10,
	FAIL_PILLAR_EXCEEDS_MAX_HEIGHT = 11,
	FAIL_PILLAR_NOT_BETWEEN_ISLANDS = 12,
	FAIL_PILLAR_ANCHOR_ILLEGAL_LOCATION = 13
}
