public enum SandboxItemType
{
	TERRAIN = 0,
	ANCHOR = 1,
	VEHICLE = 2,
	VEHICLE_STOP_TRIGGER = 3,
	WATER = 4,
	CHECKPOINT = 5,
	PLATFORM = 6,
	RAMP = 7,
	HYDRAULICS_PHASE = 8,
	VEHICLE_RESTART_PHASE = 9,
	FLYING_OBJECT = 10,
	ROCK = 11,
	ZED_AXIS_VEHICLE = 12,
	CUSTOM_SHAPE = 13,
	BUILD_ZONE = 14,
	PILLAR = 15,
	IMPOSTER = 16,
	DECOR = 17
}
