public enum WorkshopSortOrder
{
	MOST_RECENT = 0,
	MOST_LIKED = 1,
	MOST_SUBSCRIBED = 2,
	SUBSCRIBED_BY_ME = 3,
	CREATED_BY_ME = 4,
	FAVORITED_BY_ME = 5,
	CREATED_BY_FRIENDS = 6,
	FAVORITED_BY_FRIENDS = 7,
	MOST_RECENTLY_PLAYED = 8,
	BY_NAME = 9,
	NONE = 10
}
