public enum WorkshopTagType
{
	MOD = 0,
	LEVEL = 1,
	FEATURED_TAG = 2,
	ALLOWFEATURED_TAG = 3,
	SOLVED = 4,
	UNBREAKABLE = 5,
	REQUIRES_MODS = 6,
	HYDRAULICS = 7,
	HYDRAULIC_CONTROLLER = 8,
	SPRINGS = 9,
	BUILD_REGIONS = 10,
	PREBUILDS = 11,
	CUSTOM_SHAPES = 12,
	AFFECTS_GAMEPLAY = 13,
	LANGUAGE = 14,
	UGC_VEHICLES = 15,
	UGC_BOATS_PLANES = 16,
	UGC_DECOR = 17,
	UGC_CUSTOM_SHAPES = 18
}
