<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>modio.UnityPlugin</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>7.3</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnityEngine.UnityWebRequestModule">
      <HintPath>..\..\Assemblies\UnityEngine.UnityWebRequestModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\..\Assemblies\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>..\..\Assemblies\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>..\..\Assemblies\UnityEngine.UIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>..\..\Assemblies\UnityEngine.ImageConversionModule.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
    <Reference Include="UnityEngine.UnityWebRequestTextureModule">
      <HintPath>..\..\Assemblies\UnityEngine.UnityWebRequestTextureModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>..\..\Assemblies\UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="Sirenix.Utilities">
      <HintPath>..\..\Assemblies\Sirenix.Utilities.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>..\..\Assemblies\UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="Ionic.Zip.Unity">
      <HintPath>..\..\Assemblies\Ionic.Zip.Unity.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>