<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>bolt</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>7.3</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="udpkit">
      <HintPath>..\..\Assemblies\udpkit.dll</HintPath>
    </Reference>
    <Reference Include="udpkit.common">
      <HintPath>..\..\Assemblies\udpkit.common.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>..\..\Assemblies\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="udpkit.platform.photon">
      <HintPath>..\..\Assemblies\udpkit.platform.photon.dll</HintPath>
    </Reference>
    <Reference Include="PhotonRealtime">
      <HintPath>..\..\Assemblies\PhotonRealtime.dll</HintPath>
    </Reference>
    <Reference Include="udpkit.platform.null">
      <HintPath>..\..\Assemblies\udpkit.platform.null.dll</HintPath>
    </Reference>
    <Reference Include="udpkit.platform.dotnet">
      <HintPath>..\..\Assemblies\udpkit.platform.dotnet.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>