<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Meta.XR.MultiplayerBlocks.Shared</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="Oculus.VR">
      <HintPath>..\..\Assemblies\Oculus.VR.dll</HintPath>
    </Reference>
    <Reference Include="Meta.XR.BuildingBlocks">
      <HintPath>..\..\Assemblies\Meta.XR.BuildingBlocks.dll</HintPath>
    </Reference>
    <Reference Include="Oculus.Platform">
      <HintPath>..\..\Assemblies\Oculus.Platform.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
  </ItemGroup>
</Project>