namespace Heathen.SteamworksIntegration
{
	public enum SteamEventTriggerType
	{
		AchievementStored = 0,
		ActiveBeaconsUpdated = 1,
		AppResumeFromSuspend = 2,
		AvailableBeaconLocationsUpdated = 3,
		ChatMessageReceived = 4,
		ControllerConnected = 5,
		ControllerDisconnected = 6,
		DlcInstalled = 7,
		FriendRichPresenceUpdate = 8,
		GameConnectedChatJoin = 9,
		GameConnectedChatLeave = 10,
		GameConnectedFriendChatMsg = 11,
		GamepadTextInputDismissed = 12,
		GamepadTextShown = 13,
		InitializationError = 14,
		InitializationSuccess = 15,
		InputDataChanged = 16,
		InventoryDefinitionUpdate = 17,
		InventoryResultReady = 18,
		KeyboardClosed = 19,
		KeyboardShown = 20,
		LobbyAskedToLeave = 21,
		LobbyAuthenticationRequest = 22,
		LobbyChatMsg = 23,
		LobbyChatUpdate = 24,
		LobbyDataUpdate = 25,
		LobbyEnterFailed = 26,
		LobbyEnterSuccess = 27,
		LobbyGameCreated = 28,
		LobbyInvite = 29,
		LobbyJoinRequested = 30,
		LobbyLeave = 31,
		MicroTransactionAuthorizationResponse = 32,
		NewUrlLaunchParameters = 33,
		OverlayActivated = 34,
		PersonaStateChange = 35,
		RemotePlaySessionConnected = 36,
		RemotePlaySessionDisconnected = 37,
		RemoteStorageFileChanged = 38,
		ReservationNotificationCallback = 39,
		RichPresenceJoinRequested = 40,
		ScreenshotReady = 41,
		ScreenshotRequested = 42,
		ServerChangeRequested = 43,
		ServersConnectFailure = 44,
		ServersConnected = 45,
		ServersDisconnected = 46,
		ServerFavoritesListChanged = 47,
		StatsReceived = 48,
		StatsStored = 49,
		StatsUnloaded = 50
	}
}
