namespace Novell.Directory.Ldap.Events.Edir
{
	public enum EdirEventDataType
	{
		EDIR_TAG_ENTRY_EVENT_DATA = 1,
		EDIR_TAG_VALUE_EVENT_DATA = 2,
		EDIR_TAG_GENERAL_EVENT_DATA = 3,
		EDIR_TAG_SKULK_DATA = 4,
		EDIR_TAG_BINDERY_EVENT_DATA = 5,
		EDIR_TAG_DSESEV_INFO = 6,
		EDIR_TAG_MODULE_STATE_DATA = 7,
		EDIR_TAG_NETWORK_ADDRESS = 8,
		EDIR_TAG_CONNECTION_STATE = 9,
		EDIR_TAG_CHANGE_SERVER_ADDRESS = 10,
		EDIR_TAG_CHANGE_CONFIG_PARAM = 11,
		EDIR_TAG_NO_DATA = 12,
		EDIR_TAG_STATUS_LOG = 13,
		EDIR_TAG_DEBUG_EVENT_DATA = 14
	}
}
