using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using Newtonsoft.Json;
using UnityEngine;

[Serializable]
public static class InputSystem
{
	internal static Dictionary<string, InputAction> Defaults;

	internal static Dictionary<string, InputAction> Modded = new Dictionary<string, InputAction>();

	public static Dictionary<string, InputAction> Actions = new Dictionary<string, InputAction>();

	public const string FilePath = "ControlScheme.json";

	public static ActionUniverse CurrentUniverse = ActionUniverse.All;

	public static bool IsInUniverse(ActionUniverse other)
	{
		return other.UniverseMatches(CurrentUniverse);
	}

	public static void Initialise()
	{
		if (Defaults == null)
		{
			Defaults = JsonConvert.DeserializeObject<Dictionary<string, InputAction>>(Encoding.UTF8.GetString(Convert.FromBase64String("eyJwYW4iOnsiTmFtZSI6IlBhbiIsIktleSI6MzI1LCJTZWNvbmRhcnlLZXkiOjAsIkludmlzaWJsZUluTWVudSI6ZmFsc2UsIkNhdGVnb3J5IjoyLCJVbml2ZXJzZSI6MX0sInpvb21JbiI6eyJOYW1lIjoiWm9vbSBpbiIsIktleSI6NDMsIlNlY29uZGFyeUtleSI6MCwiSW52aXNpYmxlSW5NZW51Ijp0cnVlLCJDYXRlZ29yeSI6MiwiVW5pdmVyc2UiOjF9LCJ6b29tT3V0Ijp7Ik5hbWUiOiJab29tIG91dCIsIktleSI6NDUsIlNlY29uZGFyeUtleSI6MCwiSW52aXNpYmxlSW5NZW51Ijp0cnVlLCJDYXRlZ29yeSI6MiwiVW5pdmVyc2UiOjF9LCJkcmFnIjp7Ik5hbWUiOiJEcmFnIG9iamVjdCIsIktleSI6MzIzLCJTZWNvbmRhcnlLZXkiOjAsIkludmlzaWJsZUluTWVudSI6ZmFsc2UsIkNhdGVnb3J5IjowLCJVbml2ZXJzZSI6MX0sImRlbGV0ZSI6eyJOYW1lIjoiRGVsZXRlIG9iamVjdCIsIktleSI6OCwiU2Vjb25kYXJ5S2V5IjowLCJJbnZpc2libGVJbk1lbnUiOmZhbHNlLCJDYXRlZ29yeSI6MCwiVW5pdmVyc2UiOjF9LCJhY3RpdmF0ZURpcmVjdCI6eyJOYW1lIjoiQWN0aXZhdGUgb2JqZWN0IHVuZGVyIGN1cnNvciAvIGN1cnJlbnRseSBob2xkaW5nIiwiS2V5IjoxMDIsIlNlY29uZGFyeUtleSI6MCwiSW52aXNpYmxlSW5NZW51IjpmYWxzZSwiQ2F0ZWdvcnkiOjAsIlVuaXZlcnNlIjoyfSwic2xvd21vIjp7Ik5hbWUiOiJUb2dnbGUgc2xvdyBtb3Rpb24iLCJLZXkiOjEwMywiU2Vjb25kYXJ5S2V5IjowLCJJbnZpc2libGVJbk1lbnUiOmZhbHNlLCJDYXRlZ29yeSI6MCwiVW5pdmVyc2UiOjJ9LCJ0b2dnbGVMaW1iU3RhdHVzIjp7Ik5hbWUiOiJUb2dnbGUgZGV0YWlsIHZpZXciLCJLZXkiOjExNSwiU2Vjb25kYXJ5S2V5IjowLCJJbnZpc2libGVJbk1lbnUiOmZhbHNlLCJDYXRlZ29yeSI6MCwiVW5pdmVyc2UiOjJ9LCJ0aW1lIjp7Ik5hbWUiOiJUb2dnbGUgdGltZSIsIktleSI6MzIsIlNlY29uZGFyeUtleSI6MCwiSW52aXNpYmxlSW5NZW51IjpmYWxzZSwiQ2F0ZWdvcnkiOjAsIlVuaXZlcnNlIjoyfSwicGF1c2UiOnsiTmFtZSI6IlBhdXNlIG1lbnUgLyBiYWNrIiwiS2V5IjoyNywiU2Vjb25kYXJ5S2V5IjowLCJJbnZpc2libGVJbk1lbnUiOmZhbHNlLCJDYXRlZ29yeSI6MSwiVW5pdmVyc2UiOjF9LCJ0b3lib3giOnsiTmFtZSI6IlRvZ2dsZSBzaWRlcGFuZWxzIiwiS2V5Ijo5LCJTZWNvbmRhcnlLZXkiOjAsIkludmlzaWJsZUluTWVudSI6ZmFsc2UsIkNhdGVnb3J5IjoxLCJVbml2ZXJzZSI6MX0sInRvZ2dsZVVpIjp7Ik5hbWUiOiJUb2dnbGUgdXNlciBpbnRlcmZhY2UiLCJLZXkiOjk0LCJTZWNvbmRhcnlLZXkiOjAsIkludmlzaWJsZUluTWVudSI6ZmFsc2UsIkNhdGVnb3J5IjoxLCJVbml2ZXJzZSI6MX0sInRvb2xQb3dlclRvZ2dsZSI6eyJOYW1lIjoiVG9nZ2xlIGJldHdlZW4gdG9vbHMgYW5kIHBvd2VycyIsIktleSI6MzA2LCJTZWNvbmRhcnlLZXkiOjAsIkludmlzaWJsZUluTWVudSI6ZmFsc2UsIkNhdGVnb3J5IjoxLCJVbml2ZXJzZSI6Mn0sInRvb2wxIjp7Ik5hbWUiOiJTd2l0Y2ggdG8gZmlyc3QgdG9vbCIsIktleSI6NDksIlNlY29uZGFyeUtleSI6MCwiSW52aXNpYmxlSW5NZW51IjpmYWxzZSwiQ2F0ZWdvcnkiOjAsIlVuaXZlcnNlIjoyfSwidG9vbDIiOnsiTmFtZSI6IlN3aXRjaCB0byBzZWNvbmQgdG9vbCIsIktleSI6NTAsIlNlY29uZGFyeUtleSI6MCwiSW52aXNpYmxlSW5NZW51IjpmYWxzZSwiQ2F0ZWdvcnkiOjAsIlVuaXZlcnNlIjoyfSwidG9vbDMiOnsiTmFtZSI6IlN3aXRjaCB0byB0aGlyZCB0b29sIiwiS2V5Ijo1MSwiU2Vjb25kYXJ5S2V5IjowLCJJbnZpc2libGVJbk1lbnUiOmZhbHNlLCJDYXRlZ29yeSI6MCwiVW5pdmVyc2UiOjJ9LCJ0b29sNCI6eyJOYW1lIjoiU3dpdGNoIHRvIDR0aCB0b29sIiwiS2V5Ijo1MiwiU2Vjb25kYXJ5S2V5IjowLCJJbnZpc2libGVJbk1lbnUiOmZhbHNlLCJDYXRlZ29yeSI6MCwiVW5pdmVyc2UiOjJ9LCJ0b29sNSI6eyJOYW1lIjoiU3dpdGNoIHRvIDV0aCB0b29sIiwiS2V5Ijo1MywiU2Vjb25kYXJ5S2V5IjowLCJJbnZpc2libGVJbk1lbnUiOmZhbHNlLCJDYXRlZ29yeSI6MCwiVW5pdmVyc2UiOjJ9LCJ0b29sNiI6eyJOYW1lIjoiU3dpdGNoIHRvIDZ0aCB0b29sIiwiS2V5Ijo1NCwiU2Vjb25kYXJ5S2V5IjowLCJJbnZpc2libGVJbk1lbnUiOmZhbHNlLCJDYXRlZ29yeSI6MCwiVW5pdmVyc2UiOjJ9LCJ0b29sNyI6eyJOYW1lIjoiU3dpdGNoIHRvIDd0aCB0b29sIiwiS2V5Ijo1NSwiU2Vjb25kYXJ5S2V5IjowLCJJbnZpc2libGVJbk1lbnUiOmZhbHNlLCJDYXRlZ29yeSI6MCwiVW5pdmVyc2UiOjJ9LCJ0b29sOCI6eyJOYW1lIjoiU3dpdGNoIHRvIDh0aCB0b29sIiwiS2V5Ijo1NiwiU2Vjb25kYXJ5S2V5IjowLCJJbnZpc2libGVJbk1lbnUiOmZhbHNlLCJDYXRlZ29yeSI6MCwiVW5pdmVyc2UiOjJ9LCJ0b29sOSI6eyJOYW1lIjoiU3dpdGNoIHRvIDl0aCB0b29sIiwiS2V5Ijo1NywiU2Vjb25kYXJ5S2V5IjowLCJJbnZpc2libGVJbk1lbnUiOmZhbHNlLCJDYXRlZ29yeSI6MCwiVW5pdmVyc2UiOjJ9LCJzcGF3bkxlZnQiOnsiTmFtZSI6IlNwYXduIGxlZnQgZmFjaW5nIiwiS2V5IjoxMTMsIlNlY29uZGFyeUtleSI6MCwiSW52aXNpYmxlSW5NZW51IjpmYWxzZSwiQ2F0ZWdvcnkiOjAsIlVuaXZlcnNlIjoyfSwic3Bhd25SaWdodCI6eyJOYW1lIjoiU3Bhd24gcmlnaHQgZmFjaW5nIiwiS2V5IjoxMDEsIlNlY29uZGFyeUtleSI6MCwiSW52aXNpYmxlSW5NZW51IjpmYWxzZSwiQ2F0ZWdvcnkiOjAsIlVuaXZlcnNlIjoyfSwibGVmdCI6eyJOYW1lIjoiUm90YXRlIGxlZnQiLCJLZXkiOjk3LCJTZWNvbmRhcnlLZXkiOjAsIkludmlzaWJsZUluTWVudSI6ZmFsc2UsIkNhdGVnb3J5IjowLCJVbml2ZXJzZSI6MX0sInJpZ2h0Ijp7Ik5hbWUiOiJSb3RhdGUgcmlnaHQiLCJLZXkiOjEwMCwiU2Vjb25kYXJ5S2V5IjowLCJJbnZpc2libGVJbk1lbnUiOmZhbHNlLCJDYXRlZ29yeSI6MCwiVW5pdmVyc2UiOjF9LCJmYXN0Ijp7Ik5hbWUiOiJTcGVlZCB1cCByb3RhdGlvbiAvIHVuaWZvcm0gcmVzaXppbmcgLyBtdWx0aXNlbGVjdCIsIktleSI6MzA0LCJTZWNvbmRhcnlLZXkiOjAsIkludmlzaWJsZUluTWVudSI6ZmFsc2UsIkNhdGVnb3J5IjowLCJVbml2ZXJzZSI6MX0sInVuZG8iOnsiTmFtZSI6IlVuZG8iLCJLZXkiOjEyMiwiU2Vjb25kYXJ5S2V5IjowLCJJbnZpc2libGVJbk1lbnUiOmZhbHNlLCJDYXRlZ29yeSI6MCwiVW5pdmVyc2UiOjF9LCJzbmFwIjp7Ik5hbWUiOiJTbmFwIiwiS2V5IjozMDgsIlNlY29uZGFyeUtleSI6MCwiSW52aXNpYmxlSW5NZW51IjpmYWxzZSwiQ2F0ZWdvcnkiOjAsIlVuaXZlcnNlIjoxfSwic25hcFRvQ2VudGVyIjp7Ik5hbWUiOiJTbmFwIHRvIGNlbnRlciBvZiBtYXNzIiwiS2V5IjoxMDksIlNlY29uZGFyeUtleSI6MCwiSW52aXNpYmxlSW5NZW51IjpmYWxzZSwiQ2F0ZWdvcnkiOjAsIlVuaXZlcnNlIjoyfSwiY29weSI6eyJOYW1lIjoiQ29weSIsIktleSI6OTksIlNlY29uZGFyeUtleSI6MCwiSW52aXNpYmxlSW5NZW51IjpmYWxzZSwiQ2F0ZWdvcnkiOjAsIlVuaXZlcnNlIjoxfSwicGFzdGUiOnsiTmFtZSI6IlBhc3RlIiwiS2V5IjoxMTgsIlNlY29uZGFyeUtleSI6MCwiSW52aXNpYmxlSW5NZW51IjpmYWxzZSwiQ2F0ZWdvcnkiOjAsIlVuaXZlcnNlIjoxfSwiY29udGV4dCI6eyJOYW1lIjoiQ29udGV4dCBtZW51IiwiS2V5IjozMjQsIlNlY29uZGFyeUtleSI6MCwiSW52aXNpYmxlSW5NZW51IjpmYWxzZSwiQ2F0ZWdvcnkiOjAsIlVuaXZlcnNlIjoxfSwicGFuUmlnaHQiOnsiTmFtZSI6Ik1vdmUgY2FtZXJhIHJpZ2h0IiwiS2V5IjoyNzUsIlNlY29uZGFyeUtleSI6MCwiSW52aXNpYmxlSW5NZW51IjpmYWxzZSwiQ2F0ZWdvcnkiOjIsIlVuaXZlcnNlIjoxfSwicGFuTGVmdCI6eyJOYW1lIjoiTW92ZSBjYW1lcmEgbGVmdCIsIktleSI6Mjc2LCJTZWNvbmRhcnlLZXkiOjAsIkludmlzaWJsZUluTWVudSI6ZmFsc2UsIkNhdGVnb3J5IjoyLCJVbml2ZXJzZSI6MX0sInBhblVwIjp7Ik5hbWUiOiJNb3ZlIGNhbWVyYSB1cCIsIktleSI6MjczLCJTZWNvbmRhcnlLZXkiOjAsIkludmlzaWJsZUluTWVudSI6ZmFsc2UsIkNhdGVnb3J5IjoyLCJVbml2ZXJzZSI6MX0sInBhbkRvd24iOnsiTmFtZSI6Ik1vdmUgY2FtZXJhIGRvd24iLCJLZXkiOjI3NCwiU2Vjb25kYXJ5S2V5IjowLCJJbnZpc2libGVJbk1lbnUiOmZhbHNlLCJDYXRlZ29yeSI6MiwiVW5pdmVyc2UiOjF9LCJhY3RpdmF0ZUluZGlyZWN0Ijp7Ik5hbWUiOiJBY3RpdmF0ZSBvYmplY3QgdW5kZXIgY3Vyc29yIiwiS2V5IjowLCJTZWNvbmRhcnlLZXkiOjAsIkludmlzaWJsZUluTWVudSI6dHJ1ZSwiQ2F0ZWdvcnkiOjAsIlVuaXZlcnNlIjoyfSwic2VsZWN0TXVsdGlwbGUiOnsiTmFtZSI6IlNlbGVjdCBtdWx0aXBsZSIsIktleSI6MzA2LCJTZWNvbmRhcnlLZXkiOjAsIkludmlzaWJsZUluTWVudSI6ZmFsc2UsIkNhdGVnb3J5IjozLCJVbml2ZXJzZSI6M30sImxvY2FsU3BhY2VUcmFuc2Zvcm0iOnsiTmFtZSI6IkxvY2FsIHNwYWNlIHRyYW5zZm9ybWF0aW9uIiwiS2V5IjoxMDMsIlNlY29uZGFyeUtleSI6MCwiSW52aXNpYmxlSW5NZW51IjpmYWxzZSwiQ2F0ZWdvcnkiOjMsIlVuaXZlcnNlIjozfSwiaWduaXRlU2VsZWN0aW9uIjp7Ik5hbWUiOiJJZ25pdGUgc2VsZWN0ZWQgb2JqZWN0cyIsIktleSI6MCwiU2Vjb25kYXJ5S2V5IjowLCJJbnZpc2libGVJbk1lbnUiOmZhbHNlLCJDYXRlZ29yeSI6MCwiVW5pdmVyc2UiOjJ9LCJmcmVlemVTZWxlY3Rpb24iOnsiTmFtZSI6IkZyZWV6ZSBzZWxlY3RlZCBvYmplY3RzIiwiS2V5IjowLCJTZWNvbmRhcnlLZXkiOjAsIkludmlzaWJsZUluTWVudSI6ZmFsc2UsIkNhdGVnb3J5IjowLCJVbml2ZXJzZSI6Mn0sInJlc2l6ZVNlbGVjdGlvbiI6eyJOYW1lIjoiUmVzaXplIHNlbGVjdGVkIG9iamVjdHMiLCJLZXkiOjAsIlNlY29uZGFyeUtleSI6MCwiSW52aXNpYmxlSW5NZW51IjpmYWxzZSwiQ2F0ZWdvcnkiOjAsIlVuaXZlcnNlIjoyfSwiYXJyYW5nZVNlbGVjdGlvbiI6eyJOYW1lIjoiRWRpdCBsYXllcnMgb2Ygc2VsZWN0ZWQgb2JqZWN0cyIsIktleSI6MCwiU2Vjb25kYXJ5S2V5IjowLCJJbnZpc2libGVJbk1lbnUiOmZhbHNlLCJDYXRlZ29yeSI6MCwiVW5pdmVyc2UiOjJ9LCJ0b2dnbGVIb3ZlcmluZ0hpZ2hsaWdodHMiOnsiTmFtZSI6IlRvZ2dsZSBob3ZlcmluZyBoaWdobGlnaHRzIiwiS2V5IjowLCJTZWNvbmRhcnlLZXkiOjAsIkludmlzaWJsZUluTWVudSI6ZmFsc2UsIkNhdGVnb3J5IjoxLCJVbml2ZXJzZSI6Mn0sInRvZ2dsZVRoZXJtYWxWaXNpb24iOnsiTmFtZSI6IlRvZ2dsZSB0aGVybWFsIHZpc2lvbiIsIktleSI6MTE2LCJTZWNvbmRhcnlLZXkiOjAsIkludmlzaWJsZUluTWVudSI6ZmFsc2UsIkNhdGVnb3J5IjowLCJVbml2ZXJzZSI6Mn0sImV5ZWRyb3AiOnsiTmFtZSI6IkNob29zZSBvYmplY3RzIHVuZGVyIGN1cnNvciIsIktleSI6MCwiU2Vjb25kYXJ5S2V5IjowLCJJbnZpc2libGVJbk1lbnUiOmZhbHNlLCJDYXRlZ29yeSI6MCwiVW5pdmVyc2UiOjF9LCJhcnJhbmdlRG93biI6eyJOYW1lIjoiTW92ZSBsYXllciBkb3duIiwiS2V5IjowLCJTZWNvbmRhcnlLZXkiOjAsIkludmlzaWJsZUluTWVudSI6ZmFsc2UsIkNhdGVnb3J5IjowLCJVbml2ZXJzZSI6MX0sImFycmFuZ2VVcCI6eyJOYW1lIjoiTW92ZSBsYXllciB1cCIsIktleSI6MCwiU2Vjb25kYXJ5S2V5IjowLCJJbnZpc2libGVJbk1lbnUiOmZhbHNlLCJDYXRlZ29yeSI6MCwiVW5pdmVyc2UiOjF9LCJhcnJhbmdlRnJvbnQiOnsiTmFtZSI6IkJyaW5nIHRvIGZyb250IiwiS2V5IjowLCJTZWNvbmRhcnlLZXkiOjAsIkludmlzaWJsZUluTWVudSI6ZmFsc2UsIkNhdGVnb3J5IjowLCJVbml2ZXJzZSI6MX0sImFycmFuZ2VCYWNrIjp7Ik5hbWUiOiJTZW5kIHRvIGJhY2siLCJLZXkiOjAsIlNlY29uZGFyeUtleSI6MCwiSW52aXNpYmxlSW5NZW51IjpmYWxzZSwiQ2F0ZWdvcnkiOjAsIlVuaXZlcnNlIjoxfSwiaW5jcmVtZW50R3JpZCI6eyJOYW1lIjoiSW5jcmVtZW50IGdyaWQgc2l6ZSIsIktleSI6MCwiU2Vjb25kYXJ5S2V5IjowLCJJbnZpc2libGVJbk1lbnUiOmZhbHNlLCJDYXRlZ29yeSI6MCwiVW5pdmVyc2UiOjF9LCJkZWNyZW1lbnRHcmlkIjp7Ik5hbWUiOiJEZWNyZW1lbnQgZ3JpZCBzaXplIiwiS2V5IjowLCJTZWNvbmRhcnlLZXkiOjAsIkludmlzaWJsZUluTWVudSI6ZmFsc2UsIkNhdGVnb3J5IjowLCJVbml2ZXJzZSI6MX0sImluY3JlbWVudEFuZ2xlU25hcCI6eyJOYW1lIjoiSW5jcmVtZW50IGFuZ2xlIHNuYXAiLCJLZXkiOjAsIlNlY29uZGFyeUtleSI6MCwiSW52aXNpYmxlSW5NZW51IjpmYWxzZSwiQ2F0ZWdvcnkiOjAsIlVuaXZlcnNlIjoxfSwiZGVjcmVtZW50QW5nbGVTbmFwIjp7Ik5hbWUiOiJEZWNyZW1lbnQgYW5nbGUgc25hcCIsIktleSI6MCwiU2Vjb25kYXJ5S2V5IjowLCJJbnZpc2libGVJbk1lbnUiOmZhbHNlLCJDYXRlZ29yeSI6MCwiVW5pdmVyc2UiOjF9fQ==")));
		}
	}

	public static void Save()
	{
		string contents = JsonConvert.SerializeObject(Actions, Formatting.Indented);
		File.WriteAllText("ControlScheme.json", contents);
	}

	public static void ResetToDefaults()
	{
		Initialise();
		Actions.Clear();
		foreach (KeyValuePair<string, InputAction> @default in Defaults)
		{
			Actions.Add(@default.Key, @default.Value);
		}
		foreach (KeyValuePair<string, InputAction> item in Modded)
		{
			if (Actions.ContainsKey(item.Key))
			{
				Debug.LogErrorFormat("Could not add '{0}' to controls because it is already present", item.Key);
			}
			else
			{
				Actions.Add(item.Key, item.Value);
			}
		}
	}

	public static void Load()
	{
		ResetToDefaults();
		try
		{
			foreach (KeyValuePair<string, InputAction> item in JsonConvert.DeserializeObject<Dictionary<string, InputAction>>(File.ReadAllText("ControlScheme.json")))
			{
				InputAction value = item.Value;
				if (Defaults.TryGetValue(item.Key, out var value2) || Modded.TryGetValue(item.Key, out value2))
				{
					value.Name = value2.Name;
					value.Category = value2.Category;
					value.Universe = value2.Universe;
					value.InvisibleInMenu = value2.InvisibleInMenu;
				}
				else
				{
					value.Category = ActionCategory.Modded;
				}
				if (!string.IsNullOrWhiteSpace(value.Name))
				{
					if (Actions.ContainsKey(item.Key))
					{
						Actions[item.Key] = value;
					}
					else
					{
						Actions.Add(item.Key, value);
					}
				}
			}
		}
		catch (Exception)
		{
			Debug.Log("Control scheme file not found, but this is okay.");
		}
	}

	[Obsolete]
	public static void SimulatePress(string identifier)
	{
		if (Actions.TryGetValue(identifier, out var value))
		{
			value.SimulateDown();
			value.SimulateUp();
		}
	}

	public static string GetDisplayText(string name)
	{
		if (Actions.TryGetValue(name, out var value))
		{
			return value.GetDisplayText();
		}
		Debug.LogWarning("Could not retrieve control " + name);
		return "?";
	}

	public static bool Has(string name)
	{
		return Actions.ContainsKey(name);
	}

	public static bool Held(string name)
	{
		if (Actions.TryGetValue(name, out var value))
		{
			return value.IsHeld();
		}
		Debug.LogWarning("Could not retrieve control " + name);
		return false;
	}

	public static bool Down(string name)
	{
		if (Actions.TryGetValue(name, out var value))
		{
			return value.IsPressed();
		}
		Debug.LogWarning("Could not retrieve control " + name);
		return false;
	}

	public static bool Up(string name)
	{
		if (Actions.TryGetValue(name, out var value))
		{
			return value.IsReleased();
		}
		Debug.LogWarning("Could not retrieve control " + name);
		return false;
	}
}
