<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>NATTraversalForUNET</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net35</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>4</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnityEngine.Networking">
      <HintPath>..\..\Assemblies\UnityEngine.Networking.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>..\..\Assemblies\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
    <Reference Include="Open.Nat">
      <HintPath>..\..\Assemblies\Open.Nat.dll</HintPath>
    </Reference>
    <Reference Include="RakNetSwig">
      <HintPath>..\..\Assemblies\RakNetSwig.dll</HintPath>
    </Reference>
    <Reference Include="System.Threading">
      <HintPath>..\..\Assemblies\System.Threading.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>