<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>glTFast.Documentation.Examples</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="glTFast.Newtonsoft">
      <HintPath>..\..\Assemblies\glTFast.Newtonsoft.dll</HintPath>
    </Reference>
    <Reference Include="glTFast">
      <HintPath>..\..\Assemblies\glTFast.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="glTFast.Export">
      <HintPath>..\..\Assemblies\glTFast.Export.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Mathematics">
      <HintPath>..\..\Assemblies\Unity.Mathematics.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>