namespace Poly.Physics
{
	public enum Layer : byte
	{
		CollideEverything = 0,
		CollideNothing = 1,
		Terrain = 2,
		PlatformSurface = 3,
		PlatformBase_unused = 4,
		Rock = 5,
		Balloon = 6,
		CustomShape = 7,
		Vehicle = 8,
		Bridge = 9,
		AnchorNode = 10,
		SplitNode = 11,
		NonRoadNode = 12,
		RoadNode = 13,
		NonRoadEdge_unused = 14,
		RoadEdge = 15,
		RoadEdgeConnectedToSplitNode = 16,
		Bridge_End = 17,
		DebrisNonRoadNode = 18,
		DebrisRoadNode = 19,
		DebrisNonRoadEdge_unused = 20,
		DebrisRoadEdge = 21,
		CustomShape_vsNode = 22,
		CustomShape_vsRoad = 23,
		CustomShape_vsNodeAndRoad = 24,
		Fixed_CustomShape = 25,
		Fixed_CustomShape_vsNode = 26,
		Fixed_CustomShape_vsRoad = 27,
		Fixed_CustomShape_vsNodeAndRoad = 28,
		CustomShape_vsRamp = 29,
		CustomShape_vsNodeAndRamp = 30,
		CustomShape_vsRoadAndRamp = 31,
		CustomShape_vsNodeAndRoadAndRamp = 32,
		Fixed_CustomShape_vsRamp = 33,
		Fixed_CustomShape_vsNodeAndRamp = 34,
		Fixed_CustomShape_vsRoadAndRamp = 35,
		Fixed_CustomShape_vsNodeAndRoadAndRamp = 36,
		CustomShape_vsVehicles = 37,
		CustomShape_vsNodeAndVehicles = 38,
		CustomShape_vsRoadAndVehicles = 39,
		CustomShape_vsNodeAndRoadAndVehicles = 40,
		Fixed_CustomShape_vsVehicles = 41,
		Fixed_CustomShape_vsNodeAndVehicles = 42,
		Fixed_CustomShape_vsRoadAndVehicles = 43,
		Fixed_CustomShape_vsNodeAndRoadAndVehicles = 44,
		CustomShape_vsRampAndVehicles = 45,
		CustomShape_vsNodeAndRampAndVehicles = 46,
		CustomShape_vsRoadAndRampAndVehicles = 47,
		CustomShape_vsNodeAndRoadAndRampAndVehicles = 48,
		Fixed_CustomShape_vsRampAndVehicles = 49,
		Fixed_CustomShape_vsNodeAndRampAndVehicles = 50,
		Fixed_CustomShape_vsRoadAndRampAndVehicles = 51,
		Fixed_CustomShape_vsNodeAndRoadAndRampAndVehicles = 52,
		SplitRoadNode = 53,
		WaterBlock_Trigger = 54,
		VisibilityArea_Trigger = 55,
		NumValues = 56
	}
}
