namespace FMOD
{
	public enum DSP_MULTIBAND_DYNAMICS
	{
		LOWER_FREQUENCY = 0,
		UPPER_FREQUENCY = 1,
		LINKED = 2,
		USE_SIDECHAIN = 3,
		A_MODE = 4,
		A_GAIN = 5,
		A_THRESHOLD = 6,
		A_RATIO = 7,
		A_ATTACK = 8,
		A_RELEASE = 9,
		A_GAIN_MAKEUP = 10,
		A_RESPONSE_DATA = 11,
		B_MODE = 12,
		B_GAIN = 13,
		B_THRESHOLD = 14,
		B_RATIO = 15,
		B_ATTACK = 16,
		B_RELEASE = 17,
		B_GAIN_MAKEUP = 18,
		B_RESPONSE_DATA = 19,
		C_MODE = 20,
		C_GAIN = 21,
		C_THRESHOLD = 22,
		C_RATIO = 23,
		C_ATTACK = 24,
		C_RELEASE = 25,
		C_GAIN_MAKEUP = 26,
		C_RESPONSE_DATA = 27
	}
}
