namespace FMOD
{
	public enum DSP_SFXREVERB
	{
		DECAYTIME = 0,
		EARLYDELAY = 1,
		LATEDELAY = 2,
		HFREFERENCE = 3,
		HFDECAYRATIO = 4,
		DIFFUSION = 5,
		DENSITY = 6,
		LOWSHELFFREQUENCY = 7,
		LOWSHELFGAIN = 8,
		HIGHCUT = 9,
		EARLYLATEMIX = 10,
		WETLEVEL = 11,
		DRYLEVEL = 12
	}
}
