namespace PartyXBLCSharpSDK
{
	public enum PARTY_XBL_STATE_CHANGE_TYPE : uint
	{
		PARTY_XBL_STATE_CHANGE_TYPE_CREATE_LOCAL_CHAT_USER_COMPLETED = 0u,
		PARTY_XBL_STATE_CHANGE_TYPE_LOCAL_CHAT_USER_DESTROYED = 1u,
		PARTY_XBL_STATE_CHANGE_TYPE_REQUIRED_CHAT_PERMISSION_INFO_CHANGED = 2u,
		PARTY_XBL_STATE_CHANGE_TYPE_TOKEN_AND_SIGNATURE_REQUESTED = 3u,
		PARTY_XBL_STATE_CHANGE_TYPE_LOGIN_TO_PLAYFAB_COMPLETED = 4u,
		PARTY_XBL_STATE_CHANGE_TYPE_GET_ENTITY_IDS_FROM_XBOX_LIVE_USER_IDS_COMPLETED = 5u
	}
}
