namespace PartyXBLCSharpSDK
{
	public enum PARTY_XBL_CROSS_NETWORK_COMMUNICATION_PRIVACY_SETTING : uint
	{
		PARTY_XBL_CROSS_NETWORK_COMMUNICATION_PRIVACY_SETTING_ALLOWED = 0u,
		PARTY_XBL_CROSS_NETWORK_COMMUNICATION_PRIVACY_SETTING_FRIENDS_ONLY = 1u,
		PARTY_XBL_CROSS_NETWORK_COMMUNICATION_PRIVACY_SETTING_DISALLOWED = 2u
	}
}
