namespace PartyXBLCSharpSDK
{
	public enum PARTY_XBL_CHAT_PERMISSION_MASK_REASON : uint
	{
		PARTY_XBL_CHAT_PERMISSION_MASK_REASON_NO_RESTRICTION = 0u,
		PARTY_XBL_CHAT_PERMISSION_MASK_REASON_DETERMINING = 1u,
		PARTY_XBL_CHAT_PERMISSION_MASK_REASON_PRIVILEGE = 2u,
		PARTY_XBL_CHAT_PERMISSION_MASK_REASON_PRIVACY = 3u,
		PARTY_XBL_CHAT_PERMISSION_MASK_REASON_INVALID_TARGET_USER = 4u,
		PARTY_XBL_CHAT_PERMISSION_MASK_REASON_XBOX_LIVE_SERVICE_ERROR = 5u,
		PARTY_XBL_CHAT_PERMISSION_MASK_REASON_UNKNOWN_ERROR = 6u,
		PARTY_XBL_CHAT_PERMISSION_MASK_REASON_RESOLVE_USER_ISSUE = 7u
	}
}
