<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Sirenix.Serialization</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net35</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>7.3</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnityEngine">
      <HintPath>..\..\Assemblies\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
    <Reference Include="Sirenix.Serialization.Config">
      <HintPath>..\..\Assemblies\Sirenix.Serialization.Config.dll</HintPath>
    </Reference>
    <Reference Include="Sirenix.Utilities">
      <HintPath>..\..\Assemblies\Sirenix.Utilities.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>