<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Assembly-CSharp-firstpass</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net35</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>4</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="System.Core" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="UnityEngine">
      <HintPath>..\..\Assemblies\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="mcs">
      <HintPath>..\..\Assemblies\mcs.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.Networking">
      <HintPath>..\..\Assemblies\UnityEngine.Networking.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>..\..\Assemblies\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\..\Assemblies\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="Ionic.Zip.Unity">
      <HintPath>..\..\Assemblies\Ionic.Zip.Unity.dll</HintPath>
    </Reference>
    <Reference Include="NATTraversalForUNET">
      <HintPath>..\..\Assemblies\NATTraversalForUNET.dll</HintPath>
    </Reference>
    <Reference Include="System.Xml" />
  </ItemGroup>
</Project>